//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"slices"
	"sort"
	"strings"
)

// pkgName is the name of the package to generate types for.
const pkgName = "gpu"

// outputFile is the file to generate.
const outputFile = "types.go"

// inputPkg is the import path for the webgpu package.
const inputPkg = "github.com/opensraph/sraph/gpu/webgpu"

// inputDir is the relative path to the webgpu package.
const inputDir = "./webgpu"

// inputFiles is the list of files to parse.
var inputFiles = []string{
	"webgpu.go",
}

func main() {
	types, consts, comments := parseWebGPU(inputDir)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen.go. DO NOT EDIT.\n")
	buf.WriteString("package " + pkgName + "\n\n")
	buf.WriteString(fmt.Sprintf("import (\n\t\"%s\"\n)\n\n", inputPkg))

	basename := strings.Split(inputPkg, "/")[len(strings.Split(inputPkg, "/"))-1]

	// Sort for stable output
	sort.Strings(types)
	sort.Strings(consts)

	// Export all types using type alias, with comments
	for _, t := range types {
		// Skip min/max (per user instruction)
		if t == "min" || t == "max" || t == "Min" || t == "Max" {
			continue
		}
		if cmt, ok := comments[t]; ok && cmt != "" {
			// Place comment above type alias, use English comments
			lines := strings.Split(strings.TrimSpace(cmt), "\n")
			for _, line := range lines {
				buf.WriteString("// " + strings.TrimSpace(line) + "\n")
			}
		}
		buf.WriteString(fmt.Sprintf("type %s = %s.%s\n", t, basename, t))
	}

	// Export all consts using const alias, with comments
	if len(consts) > 0 {
		buf.WriteString("\nconst (\n")
		for _, c := range consts {
			if c == "min" || c == "max" || c == "Min" || c == "Max" {
				continue
			}
			if cmt, ok := comments[c]; ok && cmt != "" {
				lines := strings.Split(strings.TrimSpace(cmt), "\n")
				for _, line := range lines {
					buf.WriteString("\t// " + strings.TrimSpace(line) + "\n")
				}
			}
			buf.WriteString(fmt.Sprintf("\t%s = %s.%s\n", c, basename, c))
		}
		buf.WriteString(")\n")
	}

	formatted, err := format.Source(buf.Bytes())

	if err != nil {
		panic(fmt.Errorf("failed to format generated code: %w", err))
	}

	// Write to types.go
	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		panic(err)
	}
}

// parseWebGPU parses the webgpu package and returns exported type and const names and their comments.
func parseWebGPU(dir string) (types []string, consts []string, comments map[string]string) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !fi.IsDir() && strings.HasSuffix(fi.Name(), ".go") &&
			slices.Contains(inputFiles, fi.Name()) // Only parse the specified input files

	}, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	typemap := make(map[string]struct{})
	constmap := make(map[string]struct{})
	comments = make(map[string]string)

	for _, pkg := range pkgs {
		for _, f := range pkg.Files {
			for _, decl := range f.Decls {
				switch d := decl.(type) {
				case *ast.GenDecl:
					for _, spec := range d.Specs {
						switch s := spec.(type) {
						case *ast.TypeSpec:
							if s.Name.IsExported() {
								typemap[s.Name.Name] = struct{}{}
								if d.Doc != nil {
									comments[s.Name.Name] = d.Doc.Text()
								}
							}
						case *ast.ValueSpec:
							if d.Tok == token.CONST {
								for _, name := range s.Names {
									if name.IsExported() {
										constmap[name.Name] = struct{}{}
										if s.Doc != nil {
											comments[name.Name] = s.Doc.Text()
										} else if d.Doc != nil {
											comments[name.Name] = d.Doc.Text()
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}

	for t := range typemap {
		types = append(types, t)
	}
	for c := range constmap {
		consts = append(consts, c)
	}
	return
}
