// Code generated by gen.go. DO NOT EDIT.
package gpu

import (
	"github.com/opensraph/sraph/gpu/webgpu"
)

// Adapter interface
type Adapter = webgpu.Adapter
type AdapterInfo = webgpu.AdapterInfo
type AdapterType = webgpu.AdapterType
type AddressMode = webgpu.AddressMode
type BackendType = webgpu.BackendType

// BindGroup interface
type BindGroup = webgpu.BindGroup
type BindGroupDescriptor = webgpu.BindGroupDescriptor
type BindGroupEntry = webgpu.BindGroupEntry

// BindGroupLayout interface
type BindGroupLayout = webgpu.BindGroupLayout
type BindGroupLayoutDescriptor = webgpu.BindGroupLayoutDescriptor
type BindGroupLayoutEntry = webgpu.BindGroupLayoutEntry
type BlendComponent = webgpu.BlendComponent
type BlendFactor = webgpu.BlendFactor
type BlendOperation = webgpu.BlendOperation
type BlendState = webgpu.BlendState

// Buffer interface
type Buffer = webgpu.Buffer
type BufferBindingLayout = webgpu.BufferBindingLayout
type BufferBindingType = webgpu.BufferBindingType
type BufferDescriptor = webgpu.BufferDescriptor
type BufferMapCallback = webgpu.BufferMapCallback

// BufferMapCallbackInfo contains callback configuration
type BufferMapCallbackInfo = webgpu.BufferMapCallbackInfo
type BufferMapState = webgpu.BufferMapState
type BufferUsage = webgpu.BufferUsage

// The callback mode controls how a callback for an asynchronous operation may be fired. See @ref Asynchronous-Operations for how these are used.
type CallbackMode = webgpu.CallbackMode

// An RGBA color. Represents a `f32`, `i32`, or `u32` color using @ref DoubleAsSupertype.
//
// If any channel is non-finite, produces a @ref NonFiniteFloatValueError.
type Color = webgpu.Color
type ColorTargetState = webgpu.ColorTargetState
type ColorWriteMask = webgpu.ColorWriteMask

// CommandBuffer interface
type CommandBuffer = webgpu.CommandBuffer
type CommandBufferDescriptor = webgpu.CommandBufferDescriptor

// CommandEncoder interface
type CommandEncoder = webgpu.CommandEncoder
type CommandEncoderDescriptor = webgpu.CommandEncoderDescriptor
type CompareFunction = webgpu.CompareFunction
type CompilationInfo = webgpu.CompilationInfo
type CompilationInfoCallback = webgpu.CompilationInfoCallback

// CompilationInfoCallbackInfo contains callback configuration
type CompilationInfoCallbackInfo = webgpu.CompilationInfoCallbackInfo
type CompilationInfoRequestStatus = webgpu.CompilationInfoRequestStatus
type CompilationMessage = webgpu.CompilationMessage
type CompilationMessageType = webgpu.CompilationMessageType

// Describes how frames are composited with other contents on the screen when @ref wgpuSurfacePresent is called.
type CompositeAlphaMode = webgpu.CompositeAlphaMode
type ComputePassDescriptor = webgpu.ComputePassDescriptor

// ComputePassEncoder interface
type ComputePassEncoder = webgpu.ComputePassEncoder

// ComputePipeline interface
type ComputePipeline = webgpu.ComputePipeline
type ComputePipelineDescriptor = webgpu.ComputePipelineDescriptor
type ComputeState = webgpu.ComputeState
type ConstantEntry = webgpu.ConstantEntry
type CreateComputePipelineAsyncCallback = webgpu.CreateComputePipelineAsyncCallback

// CreateComputePipelineAsyncCallbackInfo contains callback configuration
type CreateComputePipelineAsyncCallbackInfo = webgpu.CreateComputePipelineAsyncCallbackInfo
type CreatePipelineAsyncStatus = webgpu.CreatePipelineAsyncStatus
type CreateRenderPipelineAsyncCallback = webgpu.CreateRenderPipelineAsyncCallback

// CreateRenderPipelineAsyncCallbackInfo contains callback configuration
type CreateRenderPipelineAsyncCallbackInfo = webgpu.CreateRenderPipelineAsyncCallbackInfo
type CullMode = webgpu.CullMode
type DepthStencilState = webgpu.DepthStencilState

// TODO
//
// Releasing the last ref to a `WGPUDevice` also calls @ref wgpuDeviceDestroy.
// For more info, see @ref DeviceRelease.
// Device interface
type Device = webgpu.Device
type DeviceDescriptor = webgpu.DeviceDescriptor
type DeviceLostCallback = webgpu.DeviceLostCallback

// DeviceLostCallbackInfo contains callback configuration
type DeviceLostCallbackInfo = webgpu.DeviceLostCallbackInfo
type DeviceLostReason = webgpu.DeviceLostReason
type ErrorFilter = webgpu.ErrorFilter
type ErrorType = webgpu.ErrorType
type Extent3D = webgpu.Extent3D

// See @ref WGPURequestAdapterOptions::featureLevel.
type FeatureLevel = webgpu.FeatureLevel
type FeatureName = webgpu.FeatureName
type FilterMode = webgpu.FilterMode
type FragmentState = webgpu.FragmentState
type FrontFace = webgpu.FrontFace

// Opaque handle to an asynchronous operation. See @ref Asynchronous-Operations for more information.
type Future = webgpu.Future

// Struct holding a future to wait on, and a `completed` boolean flag.
type FutureWaitInfo = webgpu.FutureWaitInfo

// GPU is the main interface for WebGPU operations
type GPU = webgpu.GPU
type IndexFormat = webgpu.IndexFormat

// Instance interface
type Instance = webgpu.Instance
type InstanceDescriptor = webgpu.InstanceDescriptor
type InstanceFeatureName = webgpu.InstanceFeatureName
type InstanceLimits = webgpu.InstanceLimits
type Limits = webgpu.Limits
type LoadOp = webgpu.LoadOp
type MapAsyncStatus = webgpu.MapAsyncStatus
type MapMode = webgpu.MapMode
type MipmapFilterMode = webgpu.MipmapFilterMode
type MultisampleState = webgpu.MultisampleState
type OptionalBool = webgpu.OptionalBool
type Origin3D = webgpu.Origin3D
type PassTimestampWrites = webgpu.PassTimestampWrites

// PipelineLayout interface
type PipelineLayout = webgpu.PipelineLayout
type PipelineLayoutDescriptor = webgpu.PipelineLayoutDescriptor
type PopErrorScopeCallback = webgpu.PopErrorScopeCallback

// PopErrorScopeCallbackInfo contains callback configuration
type PopErrorScopeCallbackInfo = webgpu.PopErrorScopeCallbackInfo
type PopErrorScopeStatus = webgpu.PopErrorScopeStatus
type PowerPreference = webgpu.PowerPreference
type PredefinedColorSpace = webgpu.PredefinedColorSpace

// Describes when and in which order frames are presented on the screen when @ref wgpuSurfacePresent is called.
type PresentMode = webgpu.PresentMode
type PrimitiveState = webgpu.PrimitiveState
type PrimitiveTopology = webgpu.PrimitiveTopology

// QuerySet interface
type QuerySet = webgpu.QuerySet
type QuerySetDescriptor = webgpu.QuerySetDescriptor
type QueryType = webgpu.QueryType

// Queue interface
type Queue = webgpu.Queue
type QueueDescriptor = webgpu.QueueDescriptor
type QueueWorkDoneCallback = webgpu.QueueWorkDoneCallback

// QueueWorkDoneCallbackInfo contains callback configuration
type QueueWorkDoneCallbackInfo = webgpu.QueueWorkDoneCallbackInfo
type QueueWorkDoneStatus = webgpu.QueueWorkDoneStatus

// RenderBundle interface
type RenderBundle = webgpu.RenderBundle
type RenderBundleDescriptor = webgpu.RenderBundleDescriptor

// RenderBundleEncoder interface
type RenderBundleEncoder = webgpu.RenderBundleEncoder
type RenderBundleEncoderDescriptor = webgpu.RenderBundleEncoderDescriptor
type RenderPassColorAttachment = webgpu.RenderPassColorAttachment
type RenderPassDepthStencilAttachment = webgpu.RenderPassDepthStencilAttachment
type RenderPassDescriptor = webgpu.RenderPassDescriptor

// RenderPassEncoder interface
type RenderPassEncoder = webgpu.RenderPassEncoder
type RenderPassMaxDrawCount = webgpu.RenderPassMaxDrawCount

// RenderPipeline interface
type RenderPipeline = webgpu.RenderPipeline
type RenderPipelineDescriptor = webgpu.RenderPipelineDescriptor
type RequestAdapterCallback = webgpu.RequestAdapterCallback

// RequestAdapterCallbackInfo contains callback configuration
type RequestAdapterCallbackInfo = webgpu.RequestAdapterCallbackInfo
type RequestAdapterOptions = webgpu.RequestAdapterOptions
type RequestAdapterStatus = webgpu.RequestAdapterStatus

// Extension providing requestAdapter options for implementations with WebXR interop (i.e. Wasm).
type RequestAdapterWebXROptions = webgpu.RequestAdapterWebXROptions
type RequestDeviceCallback = webgpu.RequestDeviceCallback

// RequestDeviceCallbackInfo contains callback configuration
type RequestDeviceCallbackInfo = webgpu.RequestDeviceCallbackInfo
type RequestDeviceStatus = webgpu.RequestDeviceStatus
type SType = webgpu.SType

// Sampler interface
type Sampler = webgpu.Sampler
type SamplerBindingLayout = webgpu.SamplerBindingLayout
type SamplerBindingType = webgpu.SamplerBindingType
type SamplerDescriptor = webgpu.SamplerDescriptor

// ShaderModule interface
type ShaderModule = webgpu.ShaderModule
type ShaderModuleDescriptor = webgpu.ShaderModuleDescriptor
type ShaderSourceSPIRV = webgpu.ShaderSourceSPIRV
type ShaderSourceWGSL = webgpu.ShaderSourceWGSL
type ShaderStage = webgpu.ShaderStage

// Status code returned (synchronously) from many operations. Generally
// indicates an invalid input like an unknown enum value or @ref OutStructChainError.
// Read the function's documentation for specific error conditions.
type Status = webgpu.Status
type StencilFaceState = webgpu.StencilFaceState
type StencilOperation = webgpu.StencilOperation
type StorageTextureAccess = webgpu.StorageTextureAccess
type StorageTextureBindingLayout = webgpu.StorageTextureBindingLayout
type StoreOp = webgpu.StoreOp
type SupportedFeatures = webgpu.SupportedFeatures
type SupportedInstanceFeatures = webgpu.SupportedInstanceFeatures
type SupportedWGSLLanguageFeatures = webgpu.SupportedWGSLLanguageFeatures

// An object used to continuously present image data to the user, see @ref Surfaces for more details.
// Surface interface
type Surface = webgpu.Surface

// Filled by @ref wgpuSurfaceGetCapabilities with what's supported for @ref wgpuSurfaceConfigure for a pair of @ref WGPUSurface and @ref WGPUAdapter.
type SurfaceCapabilities = webgpu.SurfaceCapabilities

// Extension of @ref WGPUSurfaceConfiguration for color spaces and HDR.
type SurfaceColorManagement = webgpu.SurfaceColorManagement

// Options to @ref wgpuSurfaceConfigure for defining how a @ref WGPUSurface will be rendered to and presented to the user.
// See @ref Surface-Configuration for more details.
type SurfaceConfiguration = webgpu.SurfaceConfiguration

// The root descriptor for the creation of an @ref WGPUSurface with @ref wgpuInstanceCreateSurface.
// It isn't sufficient by itself and must have one of the `WGPUSurfaceSource*` in its chain.
// See @ref Surface-Creation for more details.
type SurfaceDescriptor = webgpu.SurfaceDescriptor

// The status enum for @ref wgpuSurfaceGetCurrentTexture.
type SurfaceGetCurrentTextureStatus = webgpu.SurfaceGetCurrentTextureStatus

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping an Android [`ANativeWindow`](https://developer.android.com/ndk/reference/group/a-native-window).
type SurfaceSourceAndroidNativeWindow = webgpu.SurfaceSourceAndroidNativeWindow

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping a [`CAMetalLayer`](https://developer.apple.com/documentation/quartzcore/cametallayer?language=objc).
type SurfaceSourceMetalLayer = webgpu.SurfaceSourceMetalLayer

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping a [Wayland](https://wayland.freedesktop.org/) [`wl_surface`](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface).
type SurfaceSourceWaylandSurface = webgpu.SurfaceSourceWaylandSurface

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping a Windows [`HWND`](https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/retrieve-hwnd).
type SurfaceSourceWindowsHWND = webgpu.SurfaceSourceWindowsHWND

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping an [XCB](https://xcb.freedesktop.org/) `xcb_window_t`.
type SurfaceSourceXCBWindow = webgpu.SurfaceSourceXCBWindow

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping an [Xlib](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html) `Window`.
type SurfaceSourceXlibWindow = webgpu.SurfaceSourceXlibWindow

// Queried each frame from a @ref WGPUSurface to get a @ref WGPUTexture to render to along with some metadata.
// See @ref Surface-Presenting for more details.
type SurfaceTexture = webgpu.SurfaceTexture
type TexelCopyBufferInfo = webgpu.TexelCopyBufferInfo
type TexelCopyBufferLayout = webgpu.TexelCopyBufferLayout
type TexelCopyTextureInfo = webgpu.TexelCopyTextureInfo

// Texture interface
type Texture = webgpu.Texture
type TextureAspect = webgpu.TextureAspect
type TextureBindingLayout = webgpu.TextureBindingLayout
type TextureDescriptor = webgpu.TextureDescriptor
type TextureDimension = webgpu.TextureDimension
type TextureFormat = webgpu.TextureFormat
type TextureSampleType = webgpu.TextureSampleType
type TextureUsage = webgpu.TextureUsage

// TextureView interface
type TextureView = webgpu.TextureView
type TextureViewDescriptor = webgpu.TextureViewDescriptor
type TextureViewDimension = webgpu.TextureViewDimension
type ToneMappingMode = webgpu.ToneMappingMode
type UncapturedErrorCallback = webgpu.UncapturedErrorCallback

// UncapturedErrorCallbackInfo contains callback configuration
type UncapturedErrorCallbackInfo = webgpu.UncapturedErrorCallbackInfo
type VertexAttribute = webgpu.VertexAttribute

// If `attributes` is empty *and* `stepMode` is @ref WGPUVertexStepMode_Undefined,
// indicates a "hole" in the parent @ref WGPUVertexState `buffers` array,
// with behavior equivalent to `null` in the JS API.
//
// If `attributes` is empty but `stepMode` is *not* @ref WGPUVertexStepMode_Undefined,
// indicates a vertex buffer with no attributes, with behavior equivalent to
// `{ attributes: [] }` in the JS API. (TODO: If the JS API changes not to
// distinguish these cases, then this distinction doesn't matter and we can
// remove this documentation.)
//
// If `stepMode` is @ref WGPUVertexStepMode_Undefined but `attributes` is *not* empty,
// `stepMode` [defaults](@ref SentinelValues) to @ref WGPUVertexStepMode_Vertex.
type VertexBufferLayout = webgpu.VertexBufferLayout
type VertexFormat = webgpu.VertexFormat
type VertexState = webgpu.VertexState
type VertexStepMode = webgpu.VertexStepMode
type WGSLLanguageFeatureName = webgpu.WGSLLanguageFeatureName

// Status returned from a call to ::wgpuInstanceWaitAny.
type WaitStatus = webgpu.WaitStatus

const (
	AdapterTypeCPU           = webgpu.AdapterTypeCPU
	AdapterTypeDiscreteGPU   = webgpu.AdapterTypeDiscreteGPU
	AdapterTypeIntegratedGPU = webgpu.AdapterTypeIntegratedGPU
	AdapterTypeUnknown       = webgpu.AdapterTypeUnknown
	AddressModeClampToEdge   = webgpu.AddressModeClampToEdge
	AddressModeMirrorRepeat  = webgpu.AddressModeMirrorRepeat
	AddressModeRepeat        = webgpu.AddressModeRepeat
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	AddressModeUndefined = webgpu.AddressModeUndefined
	// Indicates no array layer count is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	ArrayLayerCountUndefined = webgpu.ArrayLayerCountUndefined
	BackendTypeD3D11         = webgpu.BackendTypeD3D11
	BackendTypeD3D12         = webgpu.BackendTypeD3D12
	BackendTypeMetal         = webgpu.BackendTypeMetal
	BackendTypeNull          = webgpu.BackendTypeNull
	BackendTypeOpenGL        = webgpu.BackendTypeOpenGL
	BackendTypeOpenGLES      = webgpu.BackendTypeOpenGLES
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	BackendTypeUndefined         = webgpu.BackendTypeUndefined
	BackendTypeVulkan            = webgpu.BackendTypeVulkan
	BackendTypeWebGPU            = webgpu.BackendTypeWebGPU
	BlendFactorConstant          = webgpu.BlendFactorConstant
	BlendFactorDst               = webgpu.BlendFactorDst
	BlendFactorDstAlpha          = webgpu.BlendFactorDstAlpha
	BlendFactorOne               = webgpu.BlendFactorOne
	BlendFactorOneMinusConstant  = webgpu.BlendFactorOneMinusConstant
	BlendFactorOneMinusDst       = webgpu.BlendFactorOneMinusDst
	BlendFactorOneMinusDstAlpha  = webgpu.BlendFactorOneMinusDstAlpha
	BlendFactorOneMinusSrc       = webgpu.BlendFactorOneMinusSrc
	BlendFactorOneMinusSrc1      = webgpu.BlendFactorOneMinusSrc1
	BlendFactorOneMinusSrc1Alpha = webgpu.BlendFactorOneMinusSrc1Alpha
	BlendFactorOneMinusSrcAlpha  = webgpu.BlendFactorOneMinusSrcAlpha
	BlendFactorSrc               = webgpu.BlendFactorSrc
	BlendFactorSrc1              = webgpu.BlendFactorSrc1
	BlendFactorSrc1Alpha         = webgpu.BlendFactorSrc1Alpha
	BlendFactorSrcAlpha          = webgpu.BlendFactorSrcAlpha
	BlendFactorSrcAlphaSaturated = webgpu.BlendFactorSrcAlphaSaturated
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	BlendFactorUndefined          = webgpu.BlendFactorUndefined
	BlendFactorZero               = webgpu.BlendFactorZero
	BlendOperationAdd             = webgpu.BlendOperationAdd
	BlendOperationMax             = webgpu.BlendOperationMax
	BlendOperationMin             = webgpu.BlendOperationMin
	BlendOperationReverseSubtract = webgpu.BlendOperationReverseSubtract
	BlendOperationSubtract        = webgpu.BlendOperationSubtract
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	BlendOperationUndefined = webgpu.BlendOperationUndefined
	// Indicates that this @ref WGPUBufferBindingLayout member of
	// its parent @ref WGPUBindGroupLayoutEntry is not used.
	// (See also @ref SentinelValues.)
	BufferBindingTypeBindingNotUsed  = webgpu.BufferBindingTypeBindingNotUsed
	BufferBindingTypeReadOnlyStorage = webgpu.BufferBindingTypeReadOnlyStorage
	BufferBindingTypeStorage         = webgpu.BufferBindingTypeStorage
	// `1`. Indicates no value is passed for this argument. See @ref SentinelValues.
	BufferBindingTypeUndefined = webgpu.BufferBindingTypeUndefined
	BufferBindingTypeUniform   = webgpu.BufferBindingTypeUniform
	BufferMapStateMapped       = webgpu.BufferMapStateMapped
	BufferMapStatePending      = webgpu.BufferMapStatePending
	BufferMapStateUnmapped     = webgpu.BufferMapStateUnmapped
	// The buffer can be used as the *destination* of a GPU-side copy operation.
	BufferUsageCopyDst = webgpu.BufferUsageCopyDst
	// The buffer can be used as the *source* of a GPU-side copy operation.
	BufferUsageCopySrc = webgpu.BufferUsageCopySrc
	// The buffer can be used as an Index buffer when doing indexed drawing in a render pipeline.
	BufferUsageIndex = webgpu.BufferUsageIndex
	// The buffer can store arguments for an indirect draw call.
	BufferUsageIndirect = webgpu.BufferUsageIndirect
	// The buffer can be *mapped* on the CPU side in *read* mode (using @ref WGPUMapMode_Read).
	BufferUsageMapRead = webgpu.BufferUsageMapRead
	// The buffer can be *mapped* on the CPU side in *write* mode (using @ref WGPUMapMode_Write).
	//
	// @note This usage is **not** required to set `mappedAtCreation` to `true` in @ref WGPUBufferDescriptor.
	BufferUsageMapWrite = webgpu.BufferUsageMapWrite
	BufferUsageNone     = webgpu.BufferUsageNone
	// The buffer can store the result of a timestamp or occlusion query.
	BufferUsageQueryResolve = webgpu.BufferUsageQueryResolve
	// The buffer can be bound to a shader as a storage buffer.
	BufferUsageStorage = webgpu.BufferUsageStorage
	// The buffer can be bound to a shader as a uniform buffer.
	BufferUsageUniform = webgpu.BufferUsageUniform
	// The buffer can be used as an Vertex buffer when using a render pipeline.
	BufferUsageVertex = webgpu.BufferUsageVertex
	// Callbacks created with `WGPUCallbackMode_AllowProcessEvents`:
	// - fire for the same reasons as callbacks created with `WGPUCallbackMode_WaitAnyOnly`
	// - fire inside a call to @ref wgpuInstanceProcessEvents if the asynchronous operation is complete.
	CallbackModeAllowProcessEvents = webgpu.CallbackModeAllowProcessEvents
	// Callbacks created with `WGPUCallbackMode_AllowSpontaneous`:
	// - fire for the same reasons as callbacks created with `WGPUCallbackMode_AllowProcessEvents`
	// - **may** fire spontaneously on an arbitrary or application thread, when the WebGPU implementations discovers that the asynchronous operation is complete.
	//
	// Implementations _should_ fire spontaneous callbacks as soon as possible.
	//
	// @note Because spontaneous callbacks may fire at an arbitrary time on an arbitrary thread, applications should take extra care when acquiring locks or mutating state inside the callback. It undefined behavior to re-entrantly call into the webgpu.h API if the callback fires while inside the callstack of another webgpu.h function that is not `wgpuInstanceWaitAny` or `wgpuInstanceProcessEvents`.
	CallbackModeAllowSpontaneous = webgpu.CallbackModeAllowSpontaneous
	// Callbacks created with `WGPUCallbackMode_WaitAnyOnly`:
	// - fire when the asynchronous operation's future is passed to a call to @ref wgpuInstanceWaitAny
	// AND the operation has already completed or it completes inside the call to @ref wgpuInstanceWaitAny.
	CallbackModeWaitAnyOnly     = webgpu.CallbackModeWaitAnyOnly
	ColorWriteMaskAll           = webgpu.ColorWriteMaskAll
	ColorWriteMaskAlpha         = webgpu.ColorWriteMaskAlpha
	ColorWriteMaskBlue          = webgpu.ColorWriteMaskBlue
	ColorWriteMaskGreen         = webgpu.ColorWriteMaskGreen
	ColorWriteMaskNone          = webgpu.ColorWriteMaskNone
	ColorWriteMaskRed           = webgpu.ColorWriteMaskRed
	CompareFunctionAlways       = webgpu.CompareFunctionAlways
	CompareFunctionEqual        = webgpu.CompareFunctionEqual
	CompareFunctionGreater      = webgpu.CompareFunctionGreater
	CompareFunctionGreaterEqual = webgpu.CompareFunctionGreaterEqual
	CompareFunctionLess         = webgpu.CompareFunctionLess
	CompareFunctionLessEqual    = webgpu.CompareFunctionLessEqual
	CompareFunctionNever        = webgpu.CompareFunctionNever
	CompareFunctionNotEqual     = webgpu.CompareFunctionNotEqual
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	CompareFunctionUndefined = webgpu.CompareFunctionUndefined
	// See @ref CallbackStatuses.
	CompilationInfoRequestStatusCallbackCancelled = webgpu.CompilationInfoRequestStatusCallbackCancelled
	CompilationInfoRequestStatusSuccess           = webgpu.CompilationInfoRequestStatusSuccess
	CompilationMessageTypeError                   = webgpu.CompilationMessageTypeError
	CompilationMessageTypeInfo                    = webgpu.CompilationMessageTypeInfo
	CompilationMessageTypeWarning                 = webgpu.CompilationMessageTypeWarning
	// Lets the WebGPU implementation choose the best mode (supported, and with the best performance) between @ref WGPUCompositeAlphaMode_Opaque or @ref WGPUCompositeAlphaMode_Inherit.
	CompositeAlphaModeAuto = webgpu.CompositeAlphaModeAuto
	// The handling of the alpha component is unknown to WebGPU and should be handled by the application using system-specific APIs. This mode may be unavailable (for example on Wasm).
	CompositeAlphaModeInherit = webgpu.CompositeAlphaModeInherit
	// The alpha component of the image is ignored and teated as if it is always 1.0.
	CompositeAlphaModeOpaque = webgpu.CompositeAlphaModeOpaque
	// The alpha component is respected and non-alpha components are assumed to be already multiplied with the alpha component. For example, (0.5, 0, 0, 0.5) is semi-transparent bright red.
	CompositeAlphaModePremultiplied = webgpu.CompositeAlphaModePremultiplied
	// The alpha component is respected and non-alpha components are assumed to NOT be already multiplied with the alpha component. For example, (1.0, 0, 0, 0.5) is semi-transparent bright red.
	CompositeAlphaModeUnpremultiplied = webgpu.CompositeAlphaModeUnpremultiplied
	// Indicates no copy stride is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	CopyStrideUndefined = webgpu.CopyStrideUndefined
	// See @ref CallbackStatuses.
	CreatePipelineAsyncStatusCallbackCancelled = webgpu.CreatePipelineAsyncStatusCallbackCancelled
	CreatePipelineAsyncStatusInternalError     = webgpu.CreatePipelineAsyncStatusInternalError
	CreatePipelineAsyncStatusSuccess           = webgpu.CreatePipelineAsyncStatusSuccess
	CreatePipelineAsyncStatusValidationError   = webgpu.CreatePipelineAsyncStatusValidationError
	CullModeBack                               = webgpu.CullModeBack
	CullModeFront                              = webgpu.CullModeFront
	CullModeNone                               = webgpu.CullModeNone
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	CullModeUndefined = webgpu.CullModeUndefined
	// Indicates no depth slice is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	DepthSliceUndefined = webgpu.DepthSliceUndefined
	// See @ref CallbackStatuses.
	DeviceLostReasonCallbackCancelled = webgpu.DeviceLostReasonCallbackCancelled
	DeviceLostReasonDestroyed         = webgpu.DeviceLostReasonDestroyed
	DeviceLostReasonFailedCreation    = webgpu.DeviceLostReasonFailedCreation
	DeviceLostReasonUnknown           = webgpu.DeviceLostReasonUnknown
	ErrorFilterInternal               = webgpu.ErrorFilterInternal
	ErrorFilterOutOfMemory            = webgpu.ErrorFilterOutOfMemory
	ErrorFilterValidation             = webgpu.ErrorFilterValidation
	ErrorTypeInternal                 = webgpu.ErrorTypeInternal
	ErrorTypeNoError                  = webgpu.ErrorTypeNoError
	ErrorTypeOutOfMemory              = webgpu.ErrorTypeOutOfMemory
	ErrorTypeUnknown                  = webgpu.ErrorTypeUnknown
	ErrorTypeValidation               = webgpu.ErrorTypeValidation
	// "Compatibility" profile which can be supported on OpenGL ES 3.1 and D3D11.
	FeatureLevelCompatibility = webgpu.FeatureLevelCompatibility
	// "Core" profile which can be supported on Vulkan/Metal/D3D12 (at least).
	FeatureLevelCore = webgpu.FeatureLevelCore
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	FeatureLevelUndefined                     = webgpu.FeatureLevelUndefined
	FeatureNameBGRA8UnormStorage              = webgpu.FeatureNameBGRA8UnormStorage
	FeatureNameClipDistances                  = webgpu.FeatureNameClipDistances
	FeatureNameDepth32FloatStencil8           = webgpu.FeatureNameDepth32FloatStencil8
	FeatureNameDepthClipControl               = webgpu.FeatureNameDepthClipControl
	FeatureNameDualSourceBlending             = webgpu.FeatureNameDualSourceBlending
	FeatureNameFloat32Blendable               = webgpu.FeatureNameFloat32Blendable
	FeatureNameFloat32Filterable              = webgpu.FeatureNameFloat32Filterable
	FeatureNameIndirectFirstInstance          = webgpu.FeatureNameIndirectFirstInstance
	FeatureNameRG11B10UfloatRenderable        = webgpu.FeatureNameRG11B10UfloatRenderable
	FeatureNameShaderF16                      = webgpu.FeatureNameShaderF16
	FeatureNameSubgroups                      = webgpu.FeatureNameSubgroups
	FeatureNameTextureCompressionASTC         = webgpu.FeatureNameTextureCompressionASTC
	FeatureNameTextureCompressionASTCSliced3D = webgpu.FeatureNameTextureCompressionASTCSliced3D
	FeatureNameTextureCompressionBC           = webgpu.FeatureNameTextureCompressionBC
	FeatureNameTextureCompressionBCSliced3D   = webgpu.FeatureNameTextureCompressionBCSliced3D
	FeatureNameTextureCompressionETC2         = webgpu.FeatureNameTextureCompressionETC2
	FeatureNameTimestampQuery                 = webgpu.FeatureNameTimestampQuery
	FilterModeLinear                          = webgpu.FilterModeLinear
	FilterModeNearest                         = webgpu.FilterModeNearest
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	FilterModeUndefined = webgpu.FilterModeUndefined
	FrontFaceCCW        = webgpu.FrontFaceCCW
	FrontFaceCW         = webgpu.FrontFaceCW
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	FrontFaceUndefined = webgpu.FrontFaceUndefined
	IndexFormatUint16  = webgpu.IndexFormatUint16
	IndexFormatUint32  = webgpu.IndexFormatUint32
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	IndexFormatUndefined = webgpu.IndexFormatUndefined
	// Normally, a @ref WGPUAdapter can only create a single device. If this is
	// available and enabled, then adapters won't immediately expire when they
	// create a device, so can be reused to make multiple devices. They may
	// still expire for other reasons.
	InstanceFeatureNameMultipleDevicesPerAdapter = webgpu.InstanceFeatureNameMultipleDevicesPerAdapter
	// Enable passing SPIR-V shaders to @ref wgpuDeviceCreateShaderModule,
	// via @ref WGPUShaderSourceSPIRV.
	InstanceFeatureNameShaderSourceSPIRV = webgpu.InstanceFeatureNameShaderSourceSPIRV
	// Enable use of ::wgpuInstanceWaitAny with `timeoutNS > 0`.
	InstanceFeatureNameTimedWaitAnyEnable = webgpu.InstanceFeatureNameTimedWaitAnyEnable
	// For `uint32_t` limits, indicates no limit value is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	LimitU32Undefined = webgpu.LimitU32Undefined
	// For `uint64_t` limits, indicates no limit value is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	LimitU64Undefined = webgpu.LimitU64Undefined
	LoadOpClear       = webgpu.LoadOpClear
	LoadOpLoad        = webgpu.LoadOpLoad
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	LoadOpUndefined       = webgpu.LoadOpUndefined
	MapAsyncStatusAborted = webgpu.MapAsyncStatusAborted
	// See @ref CallbackStatuses.
	MapAsyncStatusCallbackCancelled = webgpu.MapAsyncStatusCallbackCancelled
	MapAsyncStatusError             = webgpu.MapAsyncStatusError
	MapAsyncStatusSuccess           = webgpu.MapAsyncStatusSuccess
	MapModeNone                     = webgpu.MapModeNone
	MapModeRead                     = webgpu.MapModeRead
	MapModeWrite                    = webgpu.MapModeWrite
	// Indicates no mip level count is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	MipLevelCountUndefined  = webgpu.MipLevelCountUndefined
	MipmapFilterModeLinear  = webgpu.MipmapFilterModeLinear
	MipmapFilterModeNearest = webgpu.MipmapFilterModeNearest
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	MipmapFilterModeUndefined = webgpu.MipmapFilterModeUndefined
	OptionalBoolFalse         = webgpu.OptionalBoolFalse
	OptionalBoolTrue          = webgpu.OptionalBoolTrue
	OptionalBoolUndefined     = webgpu.OptionalBoolUndefined
	// See @ref CallbackStatuses.
	PopErrorScopeStatusCallbackCancelled = webgpu.PopErrorScopeStatusCallbackCancelled
	// The error scope stack could not be popped, because it was empty.
	PopErrorScopeStatusError = webgpu.PopErrorScopeStatusError
	// The error scope stack was successfully popped and a result was reported.
	PopErrorScopeStatusSuccess     = webgpu.PopErrorScopeStatusSuccess
	PowerPreferenceHighPerformance = webgpu.PowerPreferenceHighPerformance
	PowerPreferenceLowPower        = webgpu.PowerPreferenceLowPower
	// No preference. (See also @ref SentinelValues.)
	PowerPreferenceUndefined      = webgpu.PowerPreferenceUndefined
	PredefinedColorSpaceDisplayP3 = webgpu.PredefinedColorSpaceDisplayP3
	PredefinedColorSpaceSRGB      = webgpu.PredefinedColorSpaceSRGB
	// The presentation of the image to the user waits for the next vertical blanking period to update in a first-in, first-out manner.
	// Tearing cannot be observed and frame-loop will be limited to the display's refresh rate.
	// This is the only mode that's always available.
	PresentModeFifo = webgpu.PresentModeFifo
	// The presentation of the image to the user tries to wait for the next vertical blanking period but may decide to not wait if a frame is presented late.
	// Tearing can sometimes be observed but late-frame don't produce a full-frame stutter in the presentation.
	// This is still a first-in, first-out mechanism so a frame-loop will be limited to the display's refresh rate.
	PresentModeFifoRelaxed = webgpu.PresentModeFifoRelaxed
	// The presentation of the image to the user is updated immediately without waiting for a vertical blank.
	// Tearing can be observed but latency is minimized.
	PresentModeImmediate = webgpu.PresentModeImmediate
	// The presentation of the image to the user waits for the next vertical blanking period to update to the latest provided image.
	// Tearing cannot be observed and a frame-loop is not limited to the display's refresh rate.
	PresentModeMailbox = webgpu.PresentModeMailbox
	// Present mode is not specified. Use the default.
	PresentModeUndefined           = webgpu.PresentModeUndefined
	PrimitiveTopologyLineList      = webgpu.PrimitiveTopologyLineList
	PrimitiveTopologyLineStrip     = webgpu.PrimitiveTopologyLineStrip
	PrimitiveTopologyPointList     = webgpu.PrimitiveTopologyPointList
	PrimitiveTopologyTriangleList  = webgpu.PrimitiveTopologyTriangleList
	PrimitiveTopologyTriangleStrip = webgpu.PrimitiveTopologyTriangleStrip
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	PrimitiveTopologyUndefined = webgpu.PrimitiveTopologyUndefined
	// Indicates no query set index is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	QuerySetIndexUndefined = webgpu.QuerySetIndexUndefined
	QueryTypeOcclusion     = webgpu.QueryTypeOcclusion
	QueryTypeTimestamp     = webgpu.QueryTypeTimestamp
	// See @ref CallbackStatuses.
	QueueWorkDoneStatusCallbackCancelled = webgpu.QueueWorkDoneStatusCallbackCancelled
	// There was some deterministic error. (Note this is currently never used,
	// but it will be relevant when it's possible to create a queue object.)
	QueueWorkDoneStatusError   = webgpu.QueueWorkDoneStatusError
	QueueWorkDoneStatusSuccess = webgpu.QueueWorkDoneStatusSuccess
	// See @ref CallbackStatuses.
	RequestAdapterStatusCallbackCancelled = webgpu.RequestAdapterStatusCallbackCancelled
	RequestAdapterStatusError             = webgpu.RequestAdapterStatusError
	RequestAdapterStatusSuccess           = webgpu.RequestAdapterStatusSuccess
	RequestAdapterStatusUnavailable       = webgpu.RequestAdapterStatusUnavailable
	// See @ref CallbackStatuses.
	RequestDeviceStatusCallbackCancelled  = webgpu.RequestDeviceStatusCallbackCancelled
	RequestDeviceStatusError              = webgpu.RequestDeviceStatusError
	RequestDeviceStatusSuccess            = webgpu.RequestDeviceStatusSuccess
	STypeRenderPassMaxDrawCount           = webgpu.STypeRenderPassMaxDrawCount
	STypeRequestAdapterWebXROptions       = webgpu.STypeRequestAdapterWebXROptions
	STypeShaderSourceSPIRV                = webgpu.STypeShaderSourceSPIRV
	STypeShaderSourceWGSL                 = webgpu.STypeShaderSourceWGSL
	STypeSurfaceColorManagement           = webgpu.STypeSurfaceColorManagement
	STypeSurfaceSourceAndroidNativeWindow = webgpu.STypeSurfaceSourceAndroidNativeWindow
	STypeSurfaceSourceMetalLayer          = webgpu.STypeSurfaceSourceMetalLayer
	STypeSurfaceSourceWaylandSurface      = webgpu.STypeSurfaceSourceWaylandSurface
	STypeSurfaceSourceWindowsHWND         = webgpu.STypeSurfaceSourceWindowsHWND
	STypeSurfaceSourceXCBWindow           = webgpu.STypeSurfaceSourceXCBWindow
	STypeSurfaceSourceXlibWindow          = webgpu.STypeSurfaceSourceXlibWindow
	// Indicates that this @ref WGPUSamplerBindingLayout member of
	// its parent @ref WGPUBindGroupLayoutEntry is not used.
	// (See also @ref SentinelValues.)
	SamplerBindingTypeBindingNotUsed = webgpu.SamplerBindingTypeBindingNotUsed
	SamplerBindingTypeComparison     = webgpu.SamplerBindingTypeComparison
	SamplerBindingTypeFiltering      = webgpu.SamplerBindingTypeFiltering
	SamplerBindingTypeNonFiltering   = webgpu.SamplerBindingTypeNonFiltering
	// `1`. Indicates no value is passed for this argument. See @ref SentinelValues.
	SamplerBindingTypeUndefined    = webgpu.SamplerBindingTypeUndefined
	ShaderStageCompute             = webgpu.ShaderStageCompute
	ShaderStageFragment            = webgpu.ShaderStageFragment
	ShaderStageNone                = webgpu.ShaderStageNone
	ShaderStageVertex              = webgpu.ShaderStageVertex
	StatusError                    = webgpu.StatusError
	StatusSuccess                  = webgpu.StatusSuccess
	StencilOperationDecrementClamp = webgpu.StencilOperationDecrementClamp
	StencilOperationDecrementWrap  = webgpu.StencilOperationDecrementWrap
	StencilOperationIncrementClamp = webgpu.StencilOperationIncrementClamp
	StencilOperationIncrementWrap  = webgpu.StencilOperationIncrementWrap
	StencilOperationInvert         = webgpu.StencilOperationInvert
	StencilOperationKeep           = webgpu.StencilOperationKeep
	StencilOperationReplace        = webgpu.StencilOperationReplace
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	StencilOperationUndefined = webgpu.StencilOperationUndefined
	StencilOperationZero      = webgpu.StencilOperationZero
	// Indicates that this @ref WGPUStorageTextureBindingLayout member of
	// its parent @ref WGPUBindGroupLayoutEntry is not used.
	// (See also @ref SentinelValues.)
	StorageTextureAccessBindingNotUsed = webgpu.StorageTextureAccessBindingNotUsed
	StorageTextureAccessReadOnly       = webgpu.StorageTextureAccessReadOnly
	StorageTextureAccessReadWrite      = webgpu.StorageTextureAccessReadWrite
	// `1`. Indicates no value is passed for this argument. See @ref SentinelValues.
	StorageTextureAccessUndefined = webgpu.StorageTextureAccessUndefined
	StorageTextureAccessWriteOnly = webgpu.StorageTextureAccessWriteOnly
	StoreOpDiscard                = webgpu.StoreOpDiscard
	StoreOpStore                  = webgpu.StoreOpStore
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	StoreOpUndefined = webgpu.StoreOpUndefined
	// Sentinel value used in @ref WGPUStringView to indicate that the pointer
	// is to a null-terminated string, rather than an explicitly-sized string.
	Strlen = webgpu.Strlen
	// There was some deterministic error (for example, the surface is not configured, or there was an @ref OutStructChainError). Should produce @ref ImplementationDefinedLogging containing details.
	SurfaceGetCurrentTextureStatusError = webgpu.SurfaceGetCurrentTextureStatusError
	// The connection to whatever owns the surface was lost, or generally needs to be fully reinitialized.
	SurfaceGetCurrentTextureStatusLost = webgpu.SurfaceGetCurrentTextureStatusLost
	// The surface is too different to be used, compared to when it was originally created.
	SurfaceGetCurrentTextureStatusOutdated = webgpu.SurfaceGetCurrentTextureStatusOutdated
	// Yay! Everything is good and we can render this frame.
	SurfaceGetCurrentTextureStatusSuccessOptimal = webgpu.SurfaceGetCurrentTextureStatusSuccessOptimal
	// Still OK - the surface can present the frame, but in a suboptimal way. The surface may need reconfiguration.
	SurfaceGetCurrentTextureStatusSuccessSuboptimal = webgpu.SurfaceGetCurrentTextureStatusSuccessSuboptimal
	// Some operation timed out while trying to acquire the frame.
	SurfaceGetCurrentTextureStatusTimeout = webgpu.SurfaceGetCurrentTextureStatusTimeout
	TextureAspectAll                      = webgpu.TextureAspectAll
	TextureAspectDepthOnly                = webgpu.TextureAspectDepthOnly
	TextureAspectStencilOnly              = webgpu.TextureAspectStencilOnly
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureAspectUndefined = webgpu.TextureAspectUndefined
	TextureDimension1D     = webgpu.TextureDimension1D
	TextureDimension2D     = webgpu.TextureDimension2D
	TextureDimension3D     = webgpu.TextureDimension3D
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureDimensionUndefined         = webgpu.TextureDimensionUndefined
	TextureFormatASTC10x10Unorm       = webgpu.TextureFormatASTC10x10Unorm
	TextureFormatASTC10x10UnormSrgb   = webgpu.TextureFormatASTC10x10UnormSrgb
	TextureFormatASTC10x5Unorm        = webgpu.TextureFormatASTC10x5Unorm
	TextureFormatASTC10x5UnormSrgb    = webgpu.TextureFormatASTC10x5UnormSrgb
	TextureFormatASTC10x6Unorm        = webgpu.TextureFormatASTC10x6Unorm
	TextureFormatASTC10x6UnormSrgb    = webgpu.TextureFormatASTC10x6UnormSrgb
	TextureFormatASTC10x8Unorm        = webgpu.TextureFormatASTC10x8Unorm
	TextureFormatASTC10x8UnormSrgb    = webgpu.TextureFormatASTC10x8UnormSrgb
	TextureFormatASTC12x10Unorm       = webgpu.TextureFormatASTC12x10Unorm
	TextureFormatASTC12x10UnormSrgb   = webgpu.TextureFormatASTC12x10UnormSrgb
	TextureFormatASTC12x12Unorm       = webgpu.TextureFormatASTC12x12Unorm
	TextureFormatASTC12x12UnormSrgb   = webgpu.TextureFormatASTC12x12UnormSrgb
	TextureFormatASTC4x4Unorm         = webgpu.TextureFormatASTC4x4Unorm
	TextureFormatASTC4x4UnormSrgb     = webgpu.TextureFormatASTC4x4UnormSrgb
	TextureFormatASTC5x4Unorm         = webgpu.TextureFormatASTC5x4Unorm
	TextureFormatASTC5x4UnormSrgb     = webgpu.TextureFormatASTC5x4UnormSrgb
	TextureFormatASTC5x5Unorm         = webgpu.TextureFormatASTC5x5Unorm
	TextureFormatASTC5x5UnormSrgb     = webgpu.TextureFormatASTC5x5UnormSrgb
	TextureFormatASTC6x5Unorm         = webgpu.TextureFormatASTC6x5Unorm
	TextureFormatASTC6x5UnormSrgb     = webgpu.TextureFormatASTC6x5UnormSrgb
	TextureFormatASTC6x6Unorm         = webgpu.TextureFormatASTC6x6Unorm
	TextureFormatASTC6x6UnormSrgb     = webgpu.TextureFormatASTC6x6UnormSrgb
	TextureFormatASTC8x5Unorm         = webgpu.TextureFormatASTC8x5Unorm
	TextureFormatASTC8x5UnormSrgb     = webgpu.TextureFormatASTC8x5UnormSrgb
	TextureFormatASTC8x6Unorm         = webgpu.TextureFormatASTC8x6Unorm
	TextureFormatASTC8x6UnormSrgb     = webgpu.TextureFormatASTC8x6UnormSrgb
	TextureFormatASTC8x8Unorm         = webgpu.TextureFormatASTC8x8Unorm
	TextureFormatASTC8x8UnormSrgb     = webgpu.TextureFormatASTC8x8UnormSrgb
	TextureFormatBC1RGBAUnorm         = webgpu.TextureFormatBC1RGBAUnorm
	TextureFormatBC1RGBAUnormSrgb     = webgpu.TextureFormatBC1RGBAUnormSrgb
	TextureFormatBC2RGBAUnorm         = webgpu.TextureFormatBC2RGBAUnorm
	TextureFormatBC2RGBAUnormSrgb     = webgpu.TextureFormatBC2RGBAUnormSrgb
	TextureFormatBC3RGBAUnorm         = webgpu.TextureFormatBC3RGBAUnorm
	TextureFormatBC3RGBAUnormSrgb     = webgpu.TextureFormatBC3RGBAUnormSrgb
	TextureFormatBC4RSnorm            = webgpu.TextureFormatBC4RSnorm
	TextureFormatBC4RUnorm            = webgpu.TextureFormatBC4RUnorm
	TextureFormatBC5RGSnorm           = webgpu.TextureFormatBC5RGSnorm
	TextureFormatBC5RGUnorm           = webgpu.TextureFormatBC5RGUnorm
	TextureFormatBC6HRGBFloat         = webgpu.TextureFormatBC6HRGBFloat
	TextureFormatBC6HRGBUfloat        = webgpu.TextureFormatBC6HRGBUfloat
	TextureFormatBC7RGBAUnorm         = webgpu.TextureFormatBC7RGBAUnorm
	TextureFormatBC7RGBAUnormSrgb     = webgpu.TextureFormatBC7RGBAUnormSrgb
	TextureFormatBGRA8Unorm           = webgpu.TextureFormatBGRA8Unorm
	TextureFormatBGRA8UnormSrgb       = webgpu.TextureFormatBGRA8UnormSrgb
	TextureFormatDepth16Unorm         = webgpu.TextureFormatDepth16Unorm
	TextureFormatDepth24Plus          = webgpu.TextureFormatDepth24Plus
	TextureFormatDepth24PlusStencil8  = webgpu.TextureFormatDepth24PlusStencil8
	TextureFormatDepth32Float         = webgpu.TextureFormatDepth32Float
	TextureFormatDepth32FloatStencil8 = webgpu.TextureFormatDepth32FloatStencil8
	TextureFormatEACR11Snorm          = webgpu.TextureFormatEACR11Snorm
	TextureFormatEACR11Unorm          = webgpu.TextureFormatEACR11Unorm
	TextureFormatEACRG11Snorm         = webgpu.TextureFormatEACRG11Snorm
	TextureFormatEACRG11Unorm         = webgpu.TextureFormatEACRG11Unorm
	TextureFormatETC2RGB8A1Unorm      = webgpu.TextureFormatETC2RGB8A1Unorm
	TextureFormatETC2RGB8A1UnormSrgb  = webgpu.TextureFormatETC2RGB8A1UnormSrgb
	TextureFormatETC2RGB8Unorm        = webgpu.TextureFormatETC2RGB8Unorm
	TextureFormatETC2RGB8UnormSrgb    = webgpu.TextureFormatETC2RGB8UnormSrgb
	TextureFormatETC2RGBA8Unorm       = webgpu.TextureFormatETC2RGBA8Unorm
	TextureFormatETC2RGBA8UnormSrgb   = webgpu.TextureFormatETC2RGBA8UnormSrgb
	TextureFormatR16Float             = webgpu.TextureFormatR16Float
	TextureFormatR16Sint              = webgpu.TextureFormatR16Sint
	TextureFormatR16Uint              = webgpu.TextureFormatR16Uint
	TextureFormatR32Float             = webgpu.TextureFormatR32Float
	TextureFormatR32Sint              = webgpu.TextureFormatR32Sint
	TextureFormatR32Uint              = webgpu.TextureFormatR32Uint
	TextureFormatR8Sint               = webgpu.TextureFormatR8Sint
	TextureFormatR8Snorm              = webgpu.TextureFormatR8Snorm
	TextureFormatR8Uint               = webgpu.TextureFormatR8Uint
	TextureFormatR8Unorm              = webgpu.TextureFormatR8Unorm
	TextureFormatRG11B10Ufloat        = webgpu.TextureFormatRG11B10Ufloat
	TextureFormatRG16Float            = webgpu.TextureFormatRG16Float
	TextureFormatRG16Sint             = webgpu.TextureFormatRG16Sint
	TextureFormatRG16Uint             = webgpu.TextureFormatRG16Uint
	TextureFormatRG32Float            = webgpu.TextureFormatRG32Float
	TextureFormatRG32Sint             = webgpu.TextureFormatRG32Sint
	TextureFormatRG32Uint             = webgpu.TextureFormatRG32Uint
	TextureFormatRG8Sint              = webgpu.TextureFormatRG8Sint
	TextureFormatRG8Snorm             = webgpu.TextureFormatRG8Snorm
	TextureFormatRG8Uint              = webgpu.TextureFormatRG8Uint
	TextureFormatRG8Unorm             = webgpu.TextureFormatRG8Unorm
	TextureFormatRGB10A2Uint          = webgpu.TextureFormatRGB10A2Uint
	TextureFormatRGB10A2Unorm         = webgpu.TextureFormatRGB10A2Unorm
	TextureFormatRGB9E5Ufloat         = webgpu.TextureFormatRGB9E5Ufloat
	TextureFormatRGBA16Float          = webgpu.TextureFormatRGBA16Float
	TextureFormatRGBA16Sint           = webgpu.TextureFormatRGBA16Sint
	TextureFormatRGBA16Uint           = webgpu.TextureFormatRGBA16Uint
	TextureFormatRGBA32Float          = webgpu.TextureFormatRGBA32Float
	TextureFormatRGBA32Sint           = webgpu.TextureFormatRGBA32Sint
	TextureFormatRGBA32Uint           = webgpu.TextureFormatRGBA32Uint
	TextureFormatRGBA8Sint            = webgpu.TextureFormatRGBA8Sint
	TextureFormatRGBA8Snorm           = webgpu.TextureFormatRGBA8Snorm
	TextureFormatRGBA8Uint            = webgpu.TextureFormatRGBA8Uint
	TextureFormatRGBA8Unorm           = webgpu.TextureFormatRGBA8Unorm
	TextureFormatRGBA8UnormSrgb       = webgpu.TextureFormatRGBA8UnormSrgb
	TextureFormatStencil8             = webgpu.TextureFormatStencil8
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureFormatUndefined = webgpu.TextureFormatUndefined
	// Indicates that this @ref WGPUTextureBindingLayout member of
	// its parent @ref WGPUBindGroupLayoutEntry is not used.
	// (See also @ref SentinelValues.)
	TextureSampleTypeBindingNotUsed = webgpu.TextureSampleTypeBindingNotUsed
	TextureSampleTypeDepth          = webgpu.TextureSampleTypeDepth
	TextureSampleTypeFloat          = webgpu.TextureSampleTypeFloat
	TextureSampleTypeSint           = webgpu.TextureSampleTypeSint
	TextureSampleTypeUint           = webgpu.TextureSampleTypeUint
	// `1`. Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureSampleTypeUndefined         = webgpu.TextureSampleTypeUndefined
	TextureSampleTypeUnfilterableFloat = webgpu.TextureSampleTypeUnfilterableFloat
	TextureUsageCopyDst                = webgpu.TextureUsageCopyDst
	TextureUsageCopySrc                = webgpu.TextureUsageCopySrc
	TextureUsageNone                   = webgpu.TextureUsageNone
	TextureUsageRenderAttachment       = webgpu.TextureUsageRenderAttachment
	TextureUsageStorageBinding         = webgpu.TextureUsageStorageBinding
	TextureUsageTextureBinding         = webgpu.TextureUsageTextureBinding
	TextureViewDimension1D             = webgpu.TextureViewDimension1D
	TextureViewDimension2D             = webgpu.TextureViewDimension2D
	TextureViewDimension2DArray        = webgpu.TextureViewDimension2DArray
	TextureViewDimension3D             = webgpu.TextureViewDimension3D
	TextureViewDimensionCube           = webgpu.TextureViewDimensionCube
	TextureViewDimensionCubeArray      = webgpu.TextureViewDimensionCubeArray
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureViewDimensionUndefined = webgpu.TextureViewDimensionUndefined
	ToneMappingModeExtended       = webgpu.ToneMappingModeExtended
	ToneMappingModeStandard       = webgpu.ToneMappingModeStandard
	VertexFormatFloat16           = webgpu.VertexFormatFloat16
	VertexFormatFloat16x2         = webgpu.VertexFormatFloat16x2
	VertexFormatFloat16x4         = webgpu.VertexFormatFloat16x4
	VertexFormatFloat32           = webgpu.VertexFormatFloat32
	VertexFormatFloat32x2         = webgpu.VertexFormatFloat32x2
	VertexFormatFloat32x3         = webgpu.VertexFormatFloat32x3
	VertexFormatFloat32x4         = webgpu.VertexFormatFloat32x4
	VertexFormatSint16            = webgpu.VertexFormatSint16
	VertexFormatSint16x2          = webgpu.VertexFormatSint16x2
	VertexFormatSint16x4          = webgpu.VertexFormatSint16x4
	VertexFormatSint32            = webgpu.VertexFormatSint32
	VertexFormatSint32x2          = webgpu.VertexFormatSint32x2
	VertexFormatSint32x3          = webgpu.VertexFormatSint32x3
	VertexFormatSint32x4          = webgpu.VertexFormatSint32x4
	VertexFormatSint8             = webgpu.VertexFormatSint8
	VertexFormatSint8x2           = webgpu.VertexFormatSint8x2
	VertexFormatSint8x4           = webgpu.VertexFormatSint8x4
	VertexFormatSnorm16           = webgpu.VertexFormatSnorm16
	VertexFormatSnorm16x2         = webgpu.VertexFormatSnorm16x2
	VertexFormatSnorm16x4         = webgpu.VertexFormatSnorm16x4
	VertexFormatSnorm8            = webgpu.VertexFormatSnorm8
	VertexFormatSnorm8x2          = webgpu.VertexFormatSnorm8x2
	VertexFormatSnorm8x4          = webgpu.VertexFormatSnorm8x4
	VertexFormatUint16            = webgpu.VertexFormatUint16
	VertexFormatUint16x2          = webgpu.VertexFormatUint16x2
	VertexFormatUint16x4          = webgpu.VertexFormatUint16x4
	VertexFormatUint32            = webgpu.VertexFormatUint32
	VertexFormatUint32x2          = webgpu.VertexFormatUint32x2
	VertexFormatUint32x3          = webgpu.VertexFormatUint32x3
	VertexFormatUint32x4          = webgpu.VertexFormatUint32x4
	VertexFormatUint8             = webgpu.VertexFormatUint8
	VertexFormatUint8x2           = webgpu.VertexFormatUint8x2
	VertexFormatUint8x4           = webgpu.VertexFormatUint8x4
	VertexFormatUnorm10_10_10_2   = webgpu.VertexFormatUnorm10_10_10_2
	VertexFormatUnorm16           = webgpu.VertexFormatUnorm16
	VertexFormatUnorm16x2         = webgpu.VertexFormatUnorm16x2
	VertexFormatUnorm16x4         = webgpu.VertexFormatUnorm16x4
	VertexFormatUnorm8            = webgpu.VertexFormatUnorm8
	VertexFormatUnorm8x2          = webgpu.VertexFormatUnorm8x2
	VertexFormatUnorm8x4          = webgpu.VertexFormatUnorm8x4
	VertexFormatUnorm8x4BGRA      = webgpu.VertexFormatUnorm8x4BGRA
	VertexStepModeInstance        = webgpu.VertexStepModeInstance
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	VertexStepModeUndefined                                    = webgpu.VertexStepModeUndefined
	VertexStepModeVertex                                       = webgpu.VertexStepModeVertex
	WGSLLanguageFeatureNamePacked4x8IntegerDotProduct          = webgpu.WGSLLanguageFeatureNamePacked4x8IntegerDotProduct
	WGSLLanguageFeatureNamePointerCompositeAccess              = webgpu.WGSLLanguageFeatureNamePointerCompositeAccess
	WGSLLanguageFeatureNameReadonlyAndReadwriteStorageTextures = webgpu.WGSLLanguageFeatureNameReadonlyAndReadwriteStorageTextures
	WGSLLanguageFeatureNameUnrestrictedPointerParameters       = webgpu.WGSLLanguageFeatureNameUnrestrictedPointerParameters
	// The call was invalid for some reason (see @ref Wait-Any).
	// Should produce @ref ImplementationDefinedLogging containing details.
	WaitStatusError = webgpu.WaitStatusError
	// At least one WGPUFuture completed successfully.
	WaitStatusSuccess = webgpu.WaitStatusSuccess
	// The wait operation succeeded, but no WGPUFutures completed within the timeout.
	WaitStatusTimedOut = webgpu.WaitStatusTimedOut
	// Indicates a size extending to the end of the buffer. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	WholeMapSize = webgpu.WholeMapSize
	// Indicates a size extending to the end of the buffer. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	WholeSize = webgpu.WholeSize
)
