// Code generated by gen.go. DO NOT EDIT.

// Copyright 2019-2023 WebGPU-Native developers
//
// SPDX-License-Identifier: BSD-3-Clause

// Package gpu provides WebGPU implementation interfaces.
// **Important:** *This documentation is a Work In Progress.*
//
// This is the home of WebGPU C API specification. We define here the standard
// `webgpu.h` header that all implementations should provide.
//
// For all details where behavior is not otherwise specified, `webgpu.h` has
// the same behavior as the WebGPU specification for JavaScript on the Web.
// The WebIDL-based Web specification is mapped into C as faithfully (and
// bidirectionally) as practical/possible.
// The working draft of WebGPU can be found at <https://www.w3.org/TR/webgpu/>.
//
// The standard include directive for this header is `#include <webgpu/webgpu.h>`
// (if it is provided in a system-wide or toolchain-wide include directory).
package gpu

import (
	"math"
	"unsafe"
)

// Constants
const (
	// Indicates no array layer count is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	ArrayLayerCountUndefined = ^uint32(0)

	// Indicates no copy stride is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	CopyStrideUndefined = ^uint32(0)

	// Indicates no depth slice is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	DepthSliceUndefined = ^uint32(0)

	// For `uint32_t` limits, indicates no limit value is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	LimitU32Undefined = ^uint32(0)

	// For `uint64_t` limits, indicates no limit value is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	LimitU64Undefined = ^uint64(0)

	// Indicates no mip level count is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	MipLevelCountUndefined = ^uint32(0)

	// Indicates no query set index is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	QuerySetIndexUndefined = ^uint32(0)

	// Sentinel value used in @ref WGPUStringView to indicate that the pointer
	// is to a null-terminated string, rather than an explicitly-sized string.
	Strlen = ^uintptr(0)

	// Indicates a size extending to the end of the buffer. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	WholeMapSize = ^uintptr(0)

	// Indicates a size extending to the end of the buffer. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	WholeSize = ^uint64(0)
)

var (
	// Indicates no depth clear value is specified. For more info,
	// see @ref SentinelValues and the places that use this sentinel value.
	DepthClearValueUndefined = math.NaN()
)

type AdapterType uint32

const (
	AdapterTypeDiscreteGPU   AdapterType = 1
	AdapterTypeIntegratedGPU AdapterType = 2
	AdapterTypeCPU           AdapterType = 3
	AdapterTypeUnknown       AdapterType = 4
)

type AddressMode uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	AddressModeUndefined    AddressMode = 0
	AddressModeClampToEdge  AddressMode = 1
	AddressModeRepeat       AddressMode = 2
	AddressModeMirrorRepeat AddressMode = 3
)

type BackendType uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	BackendTypeUndefined BackendType = 0
	BackendTypeNull      BackendType = 1
	BackendTypeWebGPU    BackendType = 2
	BackendTypeD3D11     BackendType = 3
	BackendTypeD3D12     BackendType = 4
	BackendTypeMetal     BackendType = 5
	BackendTypeVulkan    BackendType = 6
	BackendTypeOpenGL    BackendType = 7
	BackendTypeOpenGLES  BackendType = 8
)

type BlendFactor uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	BlendFactorUndefined         BlendFactor = 0
	BlendFactorZero              BlendFactor = 1
	BlendFactorOne               BlendFactor = 2
	BlendFactorSrc               BlendFactor = 3
	BlendFactorOneMinusSrc       BlendFactor = 4
	BlendFactorSrcAlpha          BlendFactor = 5
	BlendFactorOneMinusSrcAlpha  BlendFactor = 6
	BlendFactorDst               BlendFactor = 7
	BlendFactorOneMinusDst       BlendFactor = 8
	BlendFactorDstAlpha          BlendFactor = 9
	BlendFactorOneMinusDstAlpha  BlendFactor = 10
	BlendFactorSrcAlphaSaturated BlendFactor = 11
	BlendFactorConstant          BlendFactor = 12
	BlendFactorOneMinusConstant  BlendFactor = 13
	BlendFactorSrc1              BlendFactor = 14
	BlendFactorOneMinusSrc1      BlendFactor = 15
	BlendFactorSrc1Alpha         BlendFactor = 16
	BlendFactorOneMinusSrc1Alpha BlendFactor = 17
)

type BlendOperation uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	BlendOperationUndefined       BlendOperation = 0
	BlendOperationAdd             BlendOperation = 1
	BlendOperationSubtract        BlendOperation = 2
	BlendOperationReverseSubtract BlendOperation = 3
	BlendOperationMin             BlendOperation = 4
	BlendOperationMax             BlendOperation = 5
)

type BufferBindingType uint32

const (
	// Indicates that this @ref WGPUBufferBindingLayout member of
	// its parent @ref WGPUBindGroupLayoutEntry is not used.
	// (See also @ref SentinelValues.)
	BufferBindingTypeBindingNotUsed BufferBindingType = 0

	// `1`. Indicates no value is passed for this argument. See @ref SentinelValues.
	BufferBindingTypeUndefined       BufferBindingType = 1
	BufferBindingTypeUniform         BufferBindingType = 2
	BufferBindingTypeStorage         BufferBindingType = 3
	BufferBindingTypeReadOnlyStorage BufferBindingType = 4
)

type BufferMapState uint32

const (
	BufferMapStateUnmapped BufferMapState = 1
	BufferMapStatePending  BufferMapState = 2
	BufferMapStateMapped   BufferMapState = 3
)

// The callback mode controls how a callback for an asynchronous operation may be fired. See @ref Asynchronous-Operations for how these are used.
type CallbackMode uint32

const (
	// Callbacks created with `WGPUCallbackMode_WaitAnyOnly`:
	// - fire when the asynchronous operation's future is passed to a call to @ref wgpuInstanceWaitAny
	//   AND the operation has already completed or it completes inside the call to @ref wgpuInstanceWaitAny.
	CallbackModeWaitAnyOnly CallbackMode = 1

	// Callbacks created with `WGPUCallbackMode_AllowProcessEvents`:
	// - fire for the same reasons as callbacks created with `WGPUCallbackMode_WaitAnyOnly`
	// - fire inside a call to @ref wgpuInstanceProcessEvents if the asynchronous operation is complete.
	CallbackModeAllowProcessEvents CallbackMode = 2

	// Callbacks created with `WGPUCallbackMode_AllowSpontaneous`:
	// - fire for the same reasons as callbacks created with `WGPUCallbackMode_AllowProcessEvents`
	// - **may** fire spontaneously on an arbitrary or application thread, when the WebGPU implementations discovers that the asynchronous operation is complete.
	//
	//   Implementations _should_ fire spontaneous callbacks as soon as possible.
	//
	// @note Because spontaneous callbacks may fire at an arbitrary time on an arbitrary thread, applications should take extra care when acquiring locks or mutating state inside the callback. It undefined behavior to re-entrantly call into the webgpu.h API if the callback fires while inside the callstack of another webgpu.h function that is not `wgpuInstanceWaitAny` or `wgpuInstanceProcessEvents`.
	CallbackModeAllowSpontaneous CallbackMode = 3
)

type CompareFunction uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	CompareFunctionUndefined    CompareFunction = 0
	CompareFunctionNever        CompareFunction = 1
	CompareFunctionLess         CompareFunction = 2
	CompareFunctionEqual        CompareFunction = 3
	CompareFunctionLessEqual    CompareFunction = 4
	CompareFunctionGreater      CompareFunction = 5
	CompareFunctionNotEqual     CompareFunction = 6
	CompareFunctionGreaterEqual CompareFunction = 7
	CompareFunctionAlways       CompareFunction = 8
)

type CompilationInfoRequestStatus uint32

const (
	CompilationInfoRequestStatusSuccess CompilationInfoRequestStatus = 1

	// See @ref CallbackStatuses.
	CompilationInfoRequestStatusCallbackCancelled CompilationInfoRequestStatus = 2
)

type CompilationMessageType uint32

const (
	CompilationMessageTypeError   CompilationMessageType = 1
	CompilationMessageTypeWarning CompilationMessageType = 2
	CompilationMessageTypeInfo    CompilationMessageType = 3
)

// Describes how frames are composited with other contents on the screen when @ref wgpuSurfacePresent is called.
type CompositeAlphaMode uint32

const (
	// Lets the WebGPU implementation choose the best mode (supported, and with the best performance) between @ref WGPUCompositeAlphaMode_Opaque or @ref WGPUCompositeAlphaMode_Inherit.
	CompositeAlphaModeAuto CompositeAlphaMode = 0

	// The alpha component of the image is ignored and teated as if it is always 1.0.
	CompositeAlphaModeOpaque CompositeAlphaMode = 1

	// The alpha component is respected and non-alpha components are assumed to be already multiplied with the alpha component. For example, (0.5, 0, 0, 0.5) is semi-transparent bright red.
	CompositeAlphaModePremultiplied CompositeAlphaMode = 2

	// The alpha component is respected and non-alpha components are assumed to NOT be already multiplied with the alpha component. For example, (1.0, 0, 0, 0.5) is semi-transparent bright red.
	CompositeAlphaModeUnpremultiplied CompositeAlphaMode = 3

	// The handling of the alpha component is unknown to WebGPU and should be handled by the application using system-specific APIs. This mode may be unavailable (for example on Wasm).
	CompositeAlphaModeInherit CompositeAlphaMode = 4
)

type CreatePipelineAsyncStatus uint32

const (
	CreatePipelineAsyncStatusSuccess CreatePipelineAsyncStatus = 1

	// See @ref CallbackStatuses.
	CreatePipelineAsyncStatusCallbackCancelled CreatePipelineAsyncStatus = 2
	CreatePipelineAsyncStatusValidationError   CreatePipelineAsyncStatus = 3
	CreatePipelineAsyncStatusInternalError     CreatePipelineAsyncStatus = 4
)

type CullMode uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	CullModeUndefined CullMode = 0
	CullModeNone      CullMode = 1
	CullModeFront     CullMode = 2
	CullModeBack      CullMode = 3
)

type DeviceLostReason uint32

const (
	DeviceLostReasonUnknown   DeviceLostReason = 1
	DeviceLostReasonDestroyed DeviceLostReason = 2

	// See @ref CallbackStatuses.
	DeviceLostReasonCallbackCancelled DeviceLostReason = 3
	DeviceLostReasonFailedCreation    DeviceLostReason = 4
)

type ErrorFilter uint32

const (
	ErrorFilterValidation  ErrorFilter = 1
	ErrorFilterOutOfMemory ErrorFilter = 2
	ErrorFilterInternal    ErrorFilter = 3
)

type ErrorType uint32

const (
	ErrorTypeNoError     ErrorType = 1
	ErrorTypeValidation  ErrorType = 2
	ErrorTypeOutOfMemory ErrorType = 3
	ErrorTypeInternal    ErrorType = 4
	ErrorTypeUnknown     ErrorType = 5
)

// See @ref WGPURequestAdapterOptions::featureLevel.
type FeatureLevel uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	FeatureLevelUndefined FeatureLevel = 0

	// "Compatibility" profile which can be supported on OpenGL ES 3.1 and D3D11.
	FeatureLevelCompatibility FeatureLevel = 1

	// "Core" profile which can be supported on Vulkan/Metal/D3D12 (at least).
	FeatureLevelCore FeatureLevel = 2
)

type FeatureName uint32

const (
	FeatureNameDepthClipControl               FeatureName = 1
	FeatureNameDepth32FloatStencil8           FeatureName = 2
	FeatureNameTimestampQuery                 FeatureName = 3
	FeatureNameTextureCompressionBC           FeatureName = 4
	FeatureNameTextureCompressionBCSliced3D   FeatureName = 5
	FeatureNameTextureCompressionETC2         FeatureName = 6
	FeatureNameTextureCompressionASTC         FeatureName = 7
	FeatureNameTextureCompressionASTCSliced3D FeatureName = 8
	FeatureNameIndirectFirstInstance          FeatureName = 9
	FeatureNameShaderF16                      FeatureName = 10
	FeatureNameRG11B10UfloatRenderable        FeatureName = 11
	FeatureNameBGRA8UnormStorage              FeatureName = 12
	FeatureNameFloat32Filterable              FeatureName = 13
	FeatureNameFloat32Blendable               FeatureName = 14
	FeatureNameClipDistances                  FeatureName = 15
	FeatureNameDualSourceBlending             FeatureName = 16
	FeatureNameSubgroups                      FeatureName = 17
)

type FilterMode uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	FilterModeUndefined FilterMode = 0
	FilterModeNearest   FilterMode = 1
	FilterModeLinear    FilterMode = 2
)

type FrontFace uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	FrontFaceUndefined FrontFace = 0
	FrontFaceCCW       FrontFace = 1
	FrontFaceCW        FrontFace = 2
)

type IndexFormat uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	IndexFormatUndefined IndexFormat = 0
	IndexFormatUint16    IndexFormat = 1
	IndexFormatUint32    IndexFormat = 2
)

type InstanceFeatureName uint32

const (
	// Enable use of ::wgpuInstanceWaitAny with `timeoutNS > 0`.
	InstanceFeatureNameTimedWaitAnyEnable InstanceFeatureName = 1

	// Enable passing SPIR-V shaders to @ref wgpuDeviceCreateShaderModule,
	// via @ref WGPUShaderSourceSPIRV.
	InstanceFeatureNameShaderSourceSPIRV InstanceFeatureName = 2

	// Normally, a @ref WGPUAdapter can only create a single device. If this is
	// available and enabled, then adapters won't immediately expire when they
	// create a device, so can be reused to make multiple devices. They may
	// still expire for other reasons.
	InstanceFeatureNameMultipleDevicesPerAdapter InstanceFeatureName = 3
)

type LoadOp uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	LoadOpUndefined LoadOp = 0
	LoadOpLoad      LoadOp = 1
	LoadOpClear     LoadOp = 2
)

type MapAsyncStatus uint32

const (
	MapAsyncStatusSuccess MapAsyncStatus = 1

	// See @ref CallbackStatuses.
	MapAsyncStatusCallbackCancelled MapAsyncStatus = 2
	MapAsyncStatusError             MapAsyncStatus = 3
	MapAsyncStatusAborted           MapAsyncStatus = 4
)

type MipmapFilterMode uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	MipmapFilterModeUndefined MipmapFilterMode = 0
	MipmapFilterModeNearest   MipmapFilterMode = 1
	MipmapFilterModeLinear    MipmapFilterMode = 2
)

type OptionalBool uint32

const (
	OptionalBoolFalse     OptionalBool = 0
	OptionalBoolTrue      OptionalBool = 1
	OptionalBoolUndefined OptionalBool = 2
)

type PopErrorScopeStatus uint32

const (
	// The error scope stack was successfully popped and a result was reported.
	PopErrorScopeStatusSuccess PopErrorScopeStatus = 1

	// See @ref CallbackStatuses.
	PopErrorScopeStatusCallbackCancelled PopErrorScopeStatus = 2

	// The error scope stack could not be popped, because it was empty.
	PopErrorScopeStatusError PopErrorScopeStatus = 3
)

type PowerPreference uint32

const (
	// No preference. (See also @ref SentinelValues.)
	PowerPreferenceUndefined       PowerPreference = 0
	PowerPreferenceLowPower        PowerPreference = 1
	PowerPreferenceHighPerformance PowerPreference = 2
)

type PredefinedColorSpace uint32

const (
	PredefinedColorSpaceSRGB      PredefinedColorSpace = 1
	PredefinedColorSpaceDisplayP3 PredefinedColorSpace = 2
)

// Describes when and in which order frames are presented on the screen when @ref wgpuSurfacePresent is called.
type PresentMode uint32

const (
	// Present mode is not specified. Use the default.
	PresentModeUndefined PresentMode = 0

	// The presentation of the image to the user waits for the next vertical blanking period to update in a first-in, first-out manner.
	// Tearing cannot be observed and frame-loop will be limited to the display's refresh rate.
	// This is the only mode that's always available.
	PresentModeFifo PresentMode = 1

	// The presentation of the image to the user tries to wait for the next vertical blanking period but may decide to not wait if a frame is presented late.
	// Tearing can sometimes be observed but late-frame don't produce a full-frame stutter in the presentation.
	// This is still a first-in, first-out mechanism so a frame-loop will be limited to the display's refresh rate.
	PresentModeFifoRelaxed PresentMode = 2

	// The presentation of the image to the user is updated immediately without waiting for a vertical blank.
	// Tearing can be observed but latency is minimized.
	PresentModeImmediate PresentMode = 3

	// The presentation of the image to the user waits for the next vertical blanking period to update to the latest provided image.
	// Tearing cannot be observed and a frame-loop is not limited to the display's refresh rate.
	PresentModeMailbox PresentMode = 4
)

type PrimitiveTopology uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	PrimitiveTopologyUndefined     PrimitiveTopology = 0
	PrimitiveTopologyPointList     PrimitiveTopology = 1
	PrimitiveTopologyLineList      PrimitiveTopology = 2
	PrimitiveTopologyLineStrip     PrimitiveTopology = 3
	PrimitiveTopologyTriangleList  PrimitiveTopology = 4
	PrimitiveTopologyTriangleStrip PrimitiveTopology = 5
)

type QueryType uint32

const (
	QueryTypeOcclusion QueryType = 1
	QueryTypeTimestamp QueryType = 2
)

type QueueWorkDoneStatus uint32

const (
	QueueWorkDoneStatusSuccess QueueWorkDoneStatus = 1

	// See @ref CallbackStatuses.
	QueueWorkDoneStatusCallbackCancelled QueueWorkDoneStatus = 2

	// There was some deterministic error. (Note this is currently never used,
	// but it will be relevant when it's possible to create a queue object.)
	QueueWorkDoneStatusError QueueWorkDoneStatus = 3
)

type RequestAdapterStatus uint32

const (
	RequestAdapterStatusSuccess RequestAdapterStatus = 1

	// See @ref CallbackStatuses.
	RequestAdapterStatusCallbackCancelled RequestAdapterStatus = 2
	RequestAdapterStatusUnavailable       RequestAdapterStatus = 3
	RequestAdapterStatusError             RequestAdapterStatus = 4
)

type RequestDeviceStatus uint32

const (
	RequestDeviceStatusSuccess RequestDeviceStatus = 1

	// See @ref CallbackStatuses.
	RequestDeviceStatusCallbackCancelled RequestDeviceStatus = 2
	RequestDeviceStatusError             RequestDeviceStatus = 3
)

type SamplerBindingType uint32

const (
	// Indicates that this @ref WGPUSamplerBindingLayout member of
	// its parent @ref WGPUBindGroupLayoutEntry is not used.
	// (See also @ref SentinelValues.)
	SamplerBindingTypeBindingNotUsed SamplerBindingType = 0

	// `1`. Indicates no value is passed for this argument. See @ref SentinelValues.
	SamplerBindingTypeUndefined    SamplerBindingType = 1
	SamplerBindingTypeFiltering    SamplerBindingType = 2
	SamplerBindingTypeNonFiltering SamplerBindingType = 3
	SamplerBindingTypeComparison   SamplerBindingType = 4
)

// Status code returned (synchronously) from many operations. Generally
// indicates an invalid input like an unknown enum value or @ref OutStructChainError.
// Read the function's documentation for specific error conditions.
type Status uint32

const (
	StatusSuccess Status = 1
	StatusError   Status = 2
)

type StencilOperation uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	StencilOperationUndefined      StencilOperation = 0
	StencilOperationKeep           StencilOperation = 1
	StencilOperationZero           StencilOperation = 2
	StencilOperationReplace        StencilOperation = 3
	StencilOperationInvert         StencilOperation = 4
	StencilOperationIncrementClamp StencilOperation = 5
	StencilOperationDecrementClamp StencilOperation = 6
	StencilOperationIncrementWrap  StencilOperation = 7
	StencilOperationDecrementWrap  StencilOperation = 8
)

type StorageTextureAccess uint32

const (
	// Indicates that this @ref WGPUStorageTextureBindingLayout member of
	// its parent @ref WGPUBindGroupLayoutEntry is not used.
	// (See also @ref SentinelValues.)
	StorageTextureAccessBindingNotUsed StorageTextureAccess = 0

	// `1`. Indicates no value is passed for this argument. See @ref SentinelValues.
	StorageTextureAccessUndefined StorageTextureAccess = 1
	StorageTextureAccessWriteOnly StorageTextureAccess = 2
	StorageTextureAccessReadOnly  StorageTextureAccess = 3
	StorageTextureAccessReadWrite StorageTextureAccess = 4
)

type StoreOp uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	StoreOpUndefined StoreOp = 0
	StoreOpStore     StoreOp = 1
	StoreOpDiscard   StoreOp = 2
)

type SType uint32

const (
	STypeShaderSourceSPIRV                SType = 1
	STypeShaderSourceWGSL                 SType = 2
	STypeRenderPassMaxDrawCount           SType = 3
	STypeSurfaceSourceMetalLayer          SType = 4
	STypeSurfaceSourceWindowsHWND         SType = 5
	STypeSurfaceSourceXlibWindow          SType = 6
	STypeSurfaceSourceWaylandSurface      SType = 7
	STypeSurfaceSourceAndroidNativeWindow SType = 8
	STypeSurfaceSourceXCBWindow           SType = 9
	STypeSurfaceColorManagement           SType = 10
	STypeRequestAdapterWebXROptions       SType = 11
)

// The status enum for @ref wgpuSurfaceGetCurrentTexture.
type SurfaceGetCurrentTextureStatus uint32

const (
	// Yay! Everything is good and we can render this frame.
	SurfaceGetCurrentTextureStatusSuccessOptimal SurfaceGetCurrentTextureStatus = 1

	// Still OK - the surface can present the frame, but in a suboptimal way. The surface may need reconfiguration.
	SurfaceGetCurrentTextureStatusSuccessSuboptimal SurfaceGetCurrentTextureStatus = 2

	// Some operation timed out while trying to acquire the frame.
	SurfaceGetCurrentTextureStatusTimeout SurfaceGetCurrentTextureStatus = 3

	// The surface is too different to be used, compared to when it was originally created.
	SurfaceGetCurrentTextureStatusOutdated SurfaceGetCurrentTextureStatus = 4

	// The connection to whatever owns the surface was lost, or generally needs to be fully reinitialized.
	SurfaceGetCurrentTextureStatusLost SurfaceGetCurrentTextureStatus = 5

	// There was some deterministic error (for example, the surface is not configured, or there was an @ref OutStructChainError). Should produce @ref ImplementationDefinedLogging containing details.
	SurfaceGetCurrentTextureStatusError SurfaceGetCurrentTextureStatus = 6
)

type TextureAspect uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureAspectUndefined   TextureAspect = 0
	TextureAspectAll         TextureAspect = 1
	TextureAspectStencilOnly TextureAspect = 2
	TextureAspectDepthOnly   TextureAspect = 3
)

type TextureDimension uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureDimensionUndefined TextureDimension = 0
	TextureDimension1D        TextureDimension = 1
	TextureDimension2D        TextureDimension = 2
	TextureDimension3D        TextureDimension = 3
)

type TextureFormat uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureFormatUndefined            TextureFormat = 0
	TextureFormatR8Unorm              TextureFormat = 1
	TextureFormatR8Snorm              TextureFormat = 2
	TextureFormatR8Uint               TextureFormat = 3
	TextureFormatR8Sint               TextureFormat = 4
	TextureFormatR16Uint              TextureFormat = 5
	TextureFormatR16Sint              TextureFormat = 6
	TextureFormatR16Float             TextureFormat = 7
	TextureFormatRG8Unorm             TextureFormat = 8
	TextureFormatRG8Snorm             TextureFormat = 9
	TextureFormatRG8Uint              TextureFormat = 10
	TextureFormatRG8Sint              TextureFormat = 11
	TextureFormatR32Float             TextureFormat = 12
	TextureFormatR32Uint              TextureFormat = 13
	TextureFormatR32Sint              TextureFormat = 14
	TextureFormatRG16Uint             TextureFormat = 15
	TextureFormatRG16Sint             TextureFormat = 16
	TextureFormatRG16Float            TextureFormat = 17
	TextureFormatRGBA8Unorm           TextureFormat = 18
	TextureFormatRGBA8UnormSrgb       TextureFormat = 19
	TextureFormatRGBA8Snorm           TextureFormat = 20
	TextureFormatRGBA8Uint            TextureFormat = 21
	TextureFormatRGBA8Sint            TextureFormat = 22
	TextureFormatBGRA8Unorm           TextureFormat = 23
	TextureFormatBGRA8UnormSrgb       TextureFormat = 24
	TextureFormatRGB10A2Uint          TextureFormat = 25
	TextureFormatRGB10A2Unorm         TextureFormat = 26
	TextureFormatRG11B10Ufloat        TextureFormat = 27
	TextureFormatRGB9E5Ufloat         TextureFormat = 28
	TextureFormatRG32Float            TextureFormat = 29
	TextureFormatRG32Uint             TextureFormat = 30
	TextureFormatRG32Sint             TextureFormat = 31
	TextureFormatRGBA16Uint           TextureFormat = 32
	TextureFormatRGBA16Sint           TextureFormat = 33
	TextureFormatRGBA16Float          TextureFormat = 34
	TextureFormatRGBA32Float          TextureFormat = 35
	TextureFormatRGBA32Uint           TextureFormat = 36
	TextureFormatRGBA32Sint           TextureFormat = 37
	TextureFormatStencil8             TextureFormat = 38
	TextureFormatDepth16Unorm         TextureFormat = 39
	TextureFormatDepth24Plus          TextureFormat = 40
	TextureFormatDepth24PlusStencil8  TextureFormat = 41
	TextureFormatDepth32Float         TextureFormat = 42
	TextureFormatDepth32FloatStencil8 TextureFormat = 43
	TextureFormatBC1RGBAUnorm         TextureFormat = 44
	TextureFormatBC1RGBAUnormSrgb     TextureFormat = 45
	TextureFormatBC2RGBAUnorm         TextureFormat = 46
	TextureFormatBC2RGBAUnormSrgb     TextureFormat = 47
	TextureFormatBC3RGBAUnorm         TextureFormat = 48
	TextureFormatBC3RGBAUnormSrgb     TextureFormat = 49
	TextureFormatBC4RUnorm            TextureFormat = 50
	TextureFormatBC4RSnorm            TextureFormat = 51
	TextureFormatBC5RGUnorm           TextureFormat = 52
	TextureFormatBC5RGSnorm           TextureFormat = 53
	TextureFormatBC6HRGBUfloat        TextureFormat = 54
	TextureFormatBC6HRGBFloat         TextureFormat = 55
	TextureFormatBC7RGBAUnorm         TextureFormat = 56
	TextureFormatBC7RGBAUnormSrgb     TextureFormat = 57
	TextureFormatETC2RGB8Unorm        TextureFormat = 58
	TextureFormatETC2RGB8UnormSrgb    TextureFormat = 59
	TextureFormatETC2RGB8A1Unorm      TextureFormat = 60
	TextureFormatETC2RGB8A1UnormSrgb  TextureFormat = 61
	TextureFormatETC2RGBA8Unorm       TextureFormat = 62
	TextureFormatETC2RGBA8UnormSrgb   TextureFormat = 63
	TextureFormatEACR11Unorm          TextureFormat = 64
	TextureFormatEACR11Snorm          TextureFormat = 65
	TextureFormatEACRG11Unorm         TextureFormat = 66
	TextureFormatEACRG11Snorm         TextureFormat = 67
	TextureFormatASTC4x4Unorm         TextureFormat = 68
	TextureFormatASTC4x4UnormSrgb     TextureFormat = 69
	TextureFormatASTC5x4Unorm         TextureFormat = 70
	TextureFormatASTC5x4UnormSrgb     TextureFormat = 71
	TextureFormatASTC5x5Unorm         TextureFormat = 72
	TextureFormatASTC5x5UnormSrgb     TextureFormat = 73
	TextureFormatASTC6x5Unorm         TextureFormat = 74
	TextureFormatASTC6x5UnormSrgb     TextureFormat = 75
	TextureFormatASTC6x6Unorm         TextureFormat = 76
	TextureFormatASTC6x6UnormSrgb     TextureFormat = 77
	TextureFormatASTC8x5Unorm         TextureFormat = 78
	TextureFormatASTC8x5UnormSrgb     TextureFormat = 79
	TextureFormatASTC8x6Unorm         TextureFormat = 80
	TextureFormatASTC8x6UnormSrgb     TextureFormat = 81
	TextureFormatASTC8x8Unorm         TextureFormat = 82
	TextureFormatASTC8x8UnormSrgb     TextureFormat = 83
	TextureFormatASTC10x5Unorm        TextureFormat = 84
	TextureFormatASTC10x5UnormSrgb    TextureFormat = 85
	TextureFormatASTC10x6Unorm        TextureFormat = 86
	TextureFormatASTC10x6UnormSrgb    TextureFormat = 87
	TextureFormatASTC10x8Unorm        TextureFormat = 88
	TextureFormatASTC10x8UnormSrgb    TextureFormat = 89
	TextureFormatASTC10x10Unorm       TextureFormat = 90
	TextureFormatASTC10x10UnormSrgb   TextureFormat = 91
	TextureFormatASTC12x10Unorm       TextureFormat = 92
	TextureFormatASTC12x10UnormSrgb   TextureFormat = 93
	TextureFormatASTC12x12Unorm       TextureFormat = 94
	TextureFormatASTC12x12UnormSrgb   TextureFormat = 95
)

type TextureSampleType uint32

const (
	// Indicates that this @ref WGPUTextureBindingLayout member of
	// its parent @ref WGPUBindGroupLayoutEntry is not used.
	// (See also @ref SentinelValues.)
	TextureSampleTypeBindingNotUsed TextureSampleType = 0

	// `1`. Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureSampleTypeUndefined         TextureSampleType = 1
	TextureSampleTypeFloat             TextureSampleType = 2
	TextureSampleTypeUnfilterableFloat TextureSampleType = 3
	TextureSampleTypeDepth             TextureSampleType = 4
	TextureSampleTypeSint              TextureSampleType = 5
	TextureSampleTypeUint              TextureSampleType = 6
)

type TextureViewDimension uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	TextureViewDimensionUndefined TextureViewDimension = 0
	TextureViewDimension1D        TextureViewDimension = 1
	TextureViewDimension2D        TextureViewDimension = 2
	TextureViewDimension2DArray   TextureViewDimension = 3
	TextureViewDimensionCube      TextureViewDimension = 4
	TextureViewDimensionCubeArray TextureViewDimension = 5
	TextureViewDimension3D        TextureViewDimension = 6
)

type ToneMappingMode uint32

const (
	ToneMappingModeStandard ToneMappingMode = 1
	ToneMappingModeExtended ToneMappingMode = 2
)

type VertexFormat uint32

const (
	VertexFormatUint8           VertexFormat = 1
	VertexFormatUint8x2         VertexFormat = 2
	VertexFormatUint8x4         VertexFormat = 3
	VertexFormatSint8           VertexFormat = 4
	VertexFormatSint8x2         VertexFormat = 5
	VertexFormatSint8x4         VertexFormat = 6
	VertexFormatUnorm8          VertexFormat = 7
	VertexFormatUnorm8x2        VertexFormat = 8
	VertexFormatUnorm8x4        VertexFormat = 9
	VertexFormatSnorm8          VertexFormat = 10
	VertexFormatSnorm8x2        VertexFormat = 11
	VertexFormatSnorm8x4        VertexFormat = 12
	VertexFormatUint16          VertexFormat = 13
	VertexFormatUint16x2        VertexFormat = 14
	VertexFormatUint16x4        VertexFormat = 15
	VertexFormatSint16          VertexFormat = 16
	VertexFormatSint16x2        VertexFormat = 17
	VertexFormatSint16x4        VertexFormat = 18
	VertexFormatUnorm16         VertexFormat = 19
	VertexFormatUnorm16x2       VertexFormat = 20
	VertexFormatUnorm16x4       VertexFormat = 21
	VertexFormatSnorm16         VertexFormat = 22
	VertexFormatSnorm16x2       VertexFormat = 23
	VertexFormatSnorm16x4       VertexFormat = 24
	VertexFormatFloat16         VertexFormat = 25
	VertexFormatFloat16x2       VertexFormat = 26
	VertexFormatFloat16x4       VertexFormat = 27
	VertexFormatFloat32         VertexFormat = 28
	VertexFormatFloat32x2       VertexFormat = 29
	VertexFormatFloat32x3       VertexFormat = 30
	VertexFormatFloat32x4       VertexFormat = 31
	VertexFormatUint32          VertexFormat = 32
	VertexFormatUint32x2        VertexFormat = 33
	VertexFormatUint32x3        VertexFormat = 34
	VertexFormatUint32x4        VertexFormat = 35
	VertexFormatSint32          VertexFormat = 36
	VertexFormatSint32x2        VertexFormat = 37
	VertexFormatSint32x3        VertexFormat = 38
	VertexFormatSint32x4        VertexFormat = 39
	VertexFormatUnorm10_10_10_2 VertexFormat = 40
	VertexFormatUnorm8x4BGRA    VertexFormat = 41
)

type VertexStepMode uint32

const (
	// Indicates no value is passed for this argument. See @ref SentinelValues.
	VertexStepModeUndefined VertexStepMode = 0
	VertexStepModeVertex    VertexStepMode = 1
	VertexStepModeInstance  VertexStepMode = 2
)

// Status returned from a call to ::wgpuInstanceWaitAny.
type WaitStatus uint32

const (
	// At least one WGPUFuture completed successfully.
	WaitStatusSuccess WaitStatus = 1

	// The wait operation succeeded, but no WGPUFutures completed within the timeout.
	WaitStatusTimedOut WaitStatus = 2

	// The call was invalid for some reason (see @ref Wait-Any).
	// Should produce @ref ImplementationDefinedLogging containing details.
	WaitStatusError WaitStatus = 3
)

type WGSLLanguageFeatureName uint32

const (
	WGSLLanguageFeatureNameReadonlyAndReadwriteStorageTextures WGSLLanguageFeatureName = 1
	WGSLLanguageFeatureNamePacked4x8IntegerDotProduct          WGSLLanguageFeatureName = 2
	WGSLLanguageFeatureNameUnrestrictedPointerParameters       WGSLLanguageFeatureName = 3
	WGSLLanguageFeatureNamePointerCompositeAccess              WGSLLanguageFeatureName = 4
)

type BufferUsage uint64

const (
	BufferUsageNone BufferUsage = 0x0000000000000000

	// The buffer can be *mapped* on the CPU side in *read* mode (using @ref WGPUMapMode_Read).
	BufferUsageMapRead BufferUsage = 0x0000000000000001

	// The buffer can be *mapped* on the CPU side in *write* mode (using @ref WGPUMapMode_Write).
	//
	// @note This usage is **not** required to set `mappedAtCreation` to `true` in @ref WGPUBufferDescriptor.
	BufferUsageMapWrite BufferUsage = 0x0000000000000002

	// The buffer can be used as the *source* of a GPU-side copy operation.
	BufferUsageCopySrc BufferUsage = 0x0000000000000004

	// The buffer can be used as the *destination* of a GPU-side copy operation.
	BufferUsageCopyDst BufferUsage = 0x0000000000000008

	// The buffer can be used as an Index buffer when doing indexed drawing in a render pipeline.
	BufferUsageIndex BufferUsage = 0x0000000000000010

	// The buffer can be used as an Vertex buffer when using a render pipeline.
	BufferUsageVertex BufferUsage = 0x0000000000000020

	// The buffer can be bound to a shader as a uniform buffer.
	BufferUsageUniform BufferUsage = 0x0000000000000040

	// The buffer can be bound to a shader as a storage buffer.
	BufferUsageStorage BufferUsage = 0x0000000000000080

	// The buffer can store arguments for an indirect draw call.
	BufferUsageIndirect BufferUsage = 0x0000000000000100

	// The buffer can store the result of a timestamp or occlusion query.
	BufferUsageQueryResolve BufferUsage = 0x0000000000000200
)

type ColorWriteMask uint64

const (
	ColorWriteMaskNone  ColorWriteMask = 0x0000000000000000
	ColorWriteMaskRed   ColorWriteMask = 0x0000000000000001
	ColorWriteMaskGreen ColorWriteMask = 0x0000000000000002
	ColorWriteMaskBlue  ColorWriteMask = 0x0000000000000004
	ColorWriteMaskAlpha ColorWriteMask = 0x0000000000000008
	ColorWriteMaskAll   ColorWriteMask = 0x000000000000000F
)

type MapMode uint64

const (
	MapModeNone  MapMode = 0x0000000000000000
	MapModeRead  MapMode = 0x0000000000000001
	MapModeWrite MapMode = 0x0000000000000002
)

type ShaderStage uint64

const (
	ShaderStageNone     ShaderStage = 0x0000000000000000
	ShaderStageVertex   ShaderStage = 0x0000000000000001
	ShaderStageFragment ShaderStage = 0x0000000000000002
	ShaderStageCompute  ShaderStage = 0x0000000000000004
)

type TextureUsage uint64

const (
	TextureUsageNone             TextureUsage = 0x0000000000000000
	TextureUsageCopySrc          TextureUsage = 0x0000000000000001
	TextureUsageCopyDst          TextureUsage = 0x0000000000000002
	TextureUsageTextureBinding   TextureUsage = 0x0000000000000004
	TextureUsageStorageBinding   TextureUsage = 0x0000000000000008
	TextureUsageRenderAttachment TextureUsage = 0x0000000000000010
)

type BufferMapCallback func(status MapAsyncStatus, message string)

// BufferMapCallbackInfo contains callback configuration
type BufferMapCallbackInfo struct {
	Mode      CallbackMode
	Callback  BufferMapCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type CompilationInfoCallback func(status CompilationInfoRequestStatus, compilationInfo CompilationInfo)

// CompilationInfoCallbackInfo contains callback configuration
type CompilationInfoCallbackInfo struct {
	Mode      CallbackMode
	Callback  CompilationInfoCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type CreateComputePipelineAsyncCallback func(status CreatePipelineAsyncStatus, pipeline ComputePipeline, message string)

// CreateComputePipelineAsyncCallbackInfo contains callback configuration
type CreateComputePipelineAsyncCallbackInfo struct {
	Mode      CallbackMode
	Callback  CreateComputePipelineAsyncCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type CreateRenderPipelineAsyncCallback func(status CreatePipelineAsyncStatus, pipeline RenderPipeline, message string)

// CreateRenderPipelineAsyncCallbackInfo contains callback configuration
type CreateRenderPipelineAsyncCallbackInfo struct {
	Mode      CallbackMode
	Callback  CreateRenderPipelineAsyncCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type DeviceLostCallback func(device Device, reason DeviceLostReason, message string)

// DeviceLostCallbackInfo contains callback configuration
type DeviceLostCallbackInfo struct {
	Mode      CallbackMode
	Callback  DeviceLostCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type PopErrorScopeCallback func(status PopErrorScopeStatus, errorType ErrorType, message string)

// PopErrorScopeCallbackInfo contains callback configuration
type PopErrorScopeCallbackInfo struct {
	Mode      CallbackMode
	Callback  PopErrorScopeCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type QueueWorkDoneCallback func(status QueueWorkDoneStatus, message string)

// QueueWorkDoneCallbackInfo contains callback configuration
type QueueWorkDoneCallbackInfo struct {
	Mode      CallbackMode
	Callback  QueueWorkDoneCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type RequestAdapterCallback func(status RequestAdapterStatus, adapter Adapter, message string)

// RequestAdapterCallbackInfo contains callback configuration
type RequestAdapterCallbackInfo struct {
	Mode      CallbackMode
	Callback  RequestAdapterCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type RequestDeviceCallback func(status RequestDeviceStatus, device Device, message string)

// RequestDeviceCallbackInfo contains callback configuration
type RequestDeviceCallbackInfo struct {
	Mode      CallbackMode
	Callback  RequestDeviceCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type UncapturedErrorCallback func(device Device, errorType ErrorType, message string)

// UncapturedErrorCallbackInfo contains callback configuration
type UncapturedErrorCallbackInfo struct {
	Callback  UncapturedErrorCallback
	Userdata1 unsafe.Pointer
	Userdata2 unsafe.Pointer
}

type AdapterInfo struct {
	Vendor          string
	Architecture    string
	Device          string
	Description     string
	BackendType     BackendType
	AdapterType     AdapterType
	VendorID        uint32
	DeviceID        uint32
	SubgroupMinSize uint32
	SubgroupMaxSize uint32
}

type BindGroupEntry struct {
	Binding     uint32
	Buffer      Buffer
	Offset      uint64
	Size        uint64
	Sampler     Sampler
	TextureView TextureView
}

type BlendComponent struct {
	Operation BlendOperation
	SrcFactor BlendFactor
	DstFactor BlendFactor
}

type BufferBindingLayout struct {
	Type             BufferBindingType
	HasDynamicOffset bool
	MinBindingSize   uint64
}

type BufferDescriptor struct {
	Label            string
	Usage            BufferUsage
	Size             uint64
	MappedAtCreation bool
}

// An RGBA color. Represents a `f32`, `i32`, or `u32` color using @ref DoubleAsSupertype.
//
// If any channel is non-finite, produces a @ref NonFiniteFloatValueError.
type Color struct {
	R float64
	G float64
	B float64
	A float64
}

type CommandBufferDescriptor struct {
	Label string
}

type CommandEncoderDescriptor struct {
	Label string
}

type CompilationMessage struct {
	Message string
	Type    CompilationMessageType
	LineNum uint64
	LinePos uint64
	Offset  uint64
	Length  uint64
}

type ConstantEntry struct {
	Key   string
	Value float64
}

type Extent3D struct {
	Width              uint32
	Height             uint32
	DepthOrArrayLayers uint32
}

// Opaque handle to an asynchronous operation. See @ref Asynchronous-Operations for more information.
type Future struct {
	Id uint64
}

type InstanceLimits struct {
	TimedWaitAnyMaxCount uintptr
}

type Limits struct {
	MaxTextureDimension1D                     uint32
	MaxTextureDimension2D                     uint32
	MaxTextureDimension3D                     uint32
	MaxTextureArrayLayers                     uint32
	MaxBindGroups                             uint32
	MaxBindGroupsPlusVertexBuffers            uint32
	MaxBindingsPerBindGroup                   uint32
	MaxDynamicUniformBuffersPerPipelineLayout uint32
	MaxDynamicStorageBuffersPerPipelineLayout uint32
	MaxSampledTexturesPerShaderStage          uint32
	MaxSamplersPerShaderStage                 uint32
	MaxStorageBuffersPerShaderStage           uint32
	MaxStorageTexturesPerShaderStage          uint32
	MaxUniformBuffersPerShaderStage           uint32
	MaxUniformBufferBindingSize               uint64
	MaxStorageBufferBindingSize               uint64
	MinUniformBufferOffsetAlignment           uint32
	MinStorageBufferOffsetAlignment           uint32
	MaxVertexBuffers                          uint32
	MaxBufferSize                             uint64
	MaxVertexAttributes                       uint32
	MaxVertexBufferArrayStride                uint32
	MaxInterStageShaderVariables              uint32
	MaxColorAttachments                       uint32
	MaxColorAttachmentBytesPerSample          uint32
	MaxComputeWorkgroupStorageSize            uint32
	MaxComputeInvocationsPerWorkgroup         uint32
	MaxComputeWorkgroupSizeX                  uint32
	MaxComputeWorkgroupSizeY                  uint32
	MaxComputeWorkgroupSizeZ                  uint32
	MaxComputeWorkgroupsPerDimension          uint32
	MaxImmediateSize                          uint32
}

type MultisampleState struct {
	Count                  uint32
	Mask                   uint32
	AlphaToCoverageEnabled bool
}

type Origin3D struct {
	X uint32
	Y uint32
	Z uint32
}

type PassTimestampWrites struct {
	QuerySet                  QuerySet
	BeginningOfPassWriteIndex uint32
	EndOfPassWriteIndex       uint32
}

type PipelineLayoutDescriptor struct {
	Label            string
	BindGroupLayouts []BindGroupLayout
	ImmediateSize    uint32
}

type PrimitiveState struct {
	Topology         PrimitiveTopology
	StripIndexFormat IndexFormat
	FrontFace        FrontFace
	CullMode         CullMode
	UnclippedDepth   bool
}

type QuerySetDescriptor struct {
	Label string
	Type  QueryType
	Count uint32
}

type QueueDescriptor struct {
	Label string
}

type RenderBundleDescriptor struct {
	Label string
}

type RenderBundleEncoderDescriptor struct {
	Label              string
	ColorFormats       []TextureFormat
	DepthStencilFormat TextureFormat
	SampleCount        uint32
	DepthReadOnly      bool
	StencilReadOnly    bool
}

type RenderPassDepthStencilAttachment struct {
	View              TextureView
	DepthLoadOp       LoadOp
	DepthStoreOp      StoreOp
	DepthClearValue   float32
	DepthReadOnly     bool
	StencilLoadOp     LoadOp
	StencilStoreOp    StoreOp
	StencilClearValue uint32
	StencilReadOnly   bool
}

type RenderPassMaxDrawCount struct {
	MaxDrawCount uint64
}

// Extension providing requestAdapter options for implementations with WebXR interop (i.e. Wasm).
type RequestAdapterWebXROptions struct {
	XrCompatible bool
}

type SamplerBindingLayout struct {
	Type SamplerBindingType
}

type SamplerDescriptor struct {
	Label         string
	AddressModeU  AddressMode
	AddressModeV  AddressMode
	AddressModeW  AddressMode
	MagFilter     FilterMode
	MinFilter     FilterMode
	MipmapFilter  MipmapFilterMode
	LodMinClamp   float32
	LodMaxClamp   float32
	Compare       CompareFunction
	MaxAnisotropy uint16
}

type ShaderSourceSPIRV struct {
	CodeSize uint32
	Code     uint32
}

type ShaderSourceWGSL struct {
	Code string
}

type StencilFaceState struct {
	Compare     CompareFunction
	FailOp      StencilOperation
	DepthFailOp StencilOperation
	PassOp      StencilOperation
}

type StorageTextureBindingLayout struct {
	Access        StorageTextureAccess
	Format        TextureFormat
	ViewDimension TextureViewDimension
}

type SupportedFeatures struct {
	Features []FeatureName
}

type SupportedInstanceFeatures struct {
	Features []InstanceFeatureName
}

type SupportedWGSLLanguageFeatures struct {
	Features []WGSLLanguageFeatureName
}

// Filled by @ref wgpuSurfaceGetCapabilities with what's supported for @ref wgpuSurfaceConfigure for a pair of @ref WGPUSurface and @ref WGPUAdapter.
type SurfaceCapabilities struct {
	Usages       TextureUsage
	Formats      []TextureFormat
	PresentModes []PresentMode
	AlphaModes   []CompositeAlphaMode
}

// Extension of @ref WGPUSurfaceConfiguration for color spaces and HDR.
type SurfaceColorManagement struct {
	ColorSpace      PredefinedColorSpace
	ToneMappingMode ToneMappingMode
}

// Options to @ref wgpuSurfaceConfigure for defining how a @ref WGPUSurface will be rendered to and presented to the user.
// See @ref Surface-Configuration for more details.
type SurfaceConfiguration struct {
	Device      Device
	Format      TextureFormat
	Usage       TextureUsage
	Width       uint32
	Height      uint32
	ViewFormats []TextureFormat
	AlphaMode   CompositeAlphaMode
	PresentMode PresentMode
}

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping an Android [`ANativeWindow`](https://developer.android.com/ndk/reference/group/a-native-window).
type SurfaceSourceAndroidNativeWindow struct {
	Window unsafe.Pointer
}

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping a [`CAMetalLayer`](https://developer.apple.com/documentation/quartzcore/cametallayer?language=objc).
type SurfaceSourceMetalLayer struct {
	Layer unsafe.Pointer
}

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping a [Wayland](https://wayland.freedesktop.org/) [`wl_surface`](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface).
type SurfaceSourceWaylandSurface struct {
	Display unsafe.Pointer
	Surface unsafe.Pointer
}

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping a Windows [`HWND`](https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/retrieve-hwnd).
type SurfaceSourceWindowsHWND struct {
	Hinstance unsafe.Pointer
	Hwnd      unsafe.Pointer
}

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping an [XCB](https://xcb.freedesktop.org/) `xcb_window_t`.
type SurfaceSourceXCBWindow struct {
	Connection unsafe.Pointer
	Window     uint32
}

// Chained in @ref WGPUSurfaceDescriptor to make an @ref WGPUSurface wrapping an [Xlib](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html) `Window`.
type SurfaceSourceXlibWindow struct {
	Display unsafe.Pointer
	Window  uint64
}

// Queried each frame from a @ref WGPUSurface to get a @ref WGPUTexture to render to along with some metadata.
// See @ref Surface-Presenting for more details.
type SurfaceTexture struct {
	Texture Texture
	Status  SurfaceGetCurrentTextureStatus
}

type TexelCopyBufferLayout struct {
	Offset       uint64
	BytesPerRow  uint32
	RowsPerImage uint32
}

type TextureBindingLayout struct {
	SampleType    TextureSampleType
	ViewDimension TextureViewDimension
	Multisampled  bool
}

type TextureViewDescriptor struct {
	Label           string
	Format          TextureFormat
	Dimension       TextureViewDimension
	BaseMipLevel    uint32
	MipLevelCount   uint32
	BaseArrayLayer  uint32
	ArrayLayerCount uint32
	Aspect          TextureAspect
	Usage           TextureUsage
}

type VertexAttribute struct {
	Format         VertexFormat
	Offset         uint64
	ShaderLocation uint32
}

type BindGroupDescriptor struct {
	Label   string
	Layout  BindGroupLayout
	Entries []BindGroupEntry
}

type BindGroupLayoutEntry struct {
	Binding          uint32
	Visibility       ShaderStage
	BindingArraySize uint32
	Buffer           BufferBindingLayout
	Sampler          SamplerBindingLayout
	Texture          TextureBindingLayout
	StorageTexture   StorageTextureBindingLayout
}

type BlendState struct {
	Color BlendComponent
	Alpha BlendComponent
}

type CompilationInfo struct {
	Messages []CompilationMessage
}

type ComputePassDescriptor struct {
	Label           string
	TimestampWrites PassTimestampWrites
}

type ComputeState struct {
	Module     ShaderModule
	EntryPoint string
	Constants  []ConstantEntry
}

type DepthStencilState struct {
	Format              TextureFormat
	DepthWriteEnabled   OptionalBool
	DepthCompare        CompareFunction
	StencilFront        StencilFaceState
	StencilBack         StencilFaceState
	StencilReadMask     uint32
	StencilWriteMask    uint32
	DepthBias           int32
	DepthBiasSlopeScale float32
	DepthBiasClamp      float32
}

type DeviceDescriptor struct {
	Label                       string
	RequiredFeatures            []FeatureName
	RequiredLimits              Limits
	DefaultQueue                QueueDescriptor
	DeviceLostCallbackInfo      DeviceLostCallbackInfo
	UncapturedErrorCallbackInfo UncapturedErrorCallbackInfo
}

// Struct holding a future to wait on, and a `completed` boolean flag.
type FutureWaitInfo struct {
	Future    Future
	Completed bool
}

type InstanceDescriptor struct {
	RequiredFeatures []InstanceFeatureName
	RequiredLimits   InstanceLimits
}

type RenderPassColorAttachment struct {
	View          TextureView
	DepthSlice    uint32
	ResolveTarget TextureView
	LoadOp        LoadOp
	StoreOp       StoreOp
	ClearValue    Color
}

type RequestAdapterOptions struct {
	FeatureLevel         FeatureLevel
	PowerPreference      PowerPreference
	ForceFallbackAdapter bool
	BackendType          BackendType
	CompatibleSurface    Surface
}

type ShaderModuleDescriptor struct {
	Label string
}

// The root descriptor for the creation of an @ref WGPUSurface with @ref wgpuInstanceCreateSurface.
// It isn't sufficient by itself and must have one of the `WGPUSurfaceSource*` in its chain.
// See @ref Surface-Creation for more details.
type SurfaceDescriptor struct {
	Label string
}

type TexelCopyBufferInfo struct {
	Layout TexelCopyBufferLayout
	Buffer Buffer
}

type TexelCopyTextureInfo struct {
	Texture  Texture
	MipLevel uint32
	Origin   Origin3D
	Aspect   TextureAspect
}

type TextureDescriptor struct {
	Label         string
	Usage         TextureUsage
	Dimension     TextureDimension
	Size          Extent3D
	Format        TextureFormat
	MipLevelCount uint32
	SampleCount   uint32
	ViewFormats   []TextureFormat
}

// If `attributes` is empty *and* `stepMode` is @ref WGPUVertexStepMode_Undefined,
// indicates a "hole" in the parent @ref WGPUVertexState `buffers` array,
// with behavior equivalent to `null` in the JS API.
//
// If `attributes` is empty but `stepMode` is *not* @ref WGPUVertexStepMode_Undefined,
// indicates a vertex buffer with no attributes, with behavior equivalent to
// `{ attributes: [] }` in the JS API. (TODO: If the JS API changes not to
// distinguish these cases, then this distinction doesn't matter and we can
// remove this documentation.)
//
// If `stepMode` is @ref WGPUVertexStepMode_Undefined but `attributes` is *not* empty,
// `stepMode` [defaults](@ref SentinelValues) to @ref WGPUVertexStepMode_Vertex.
type VertexBufferLayout struct {
	StepMode    VertexStepMode
	ArrayStride uint64
	Attributes  []VertexAttribute
}

type BindGroupLayoutDescriptor struct {
	Label   string
	Entries []BindGroupLayoutEntry
}

type ColorTargetState struct {
	Format    TextureFormat
	Blend     BlendState
	WriteMask ColorWriteMask
}

type ComputePipelineDescriptor struct {
	Label   string
	Layout  PipelineLayout
	Compute ComputeState
}

type RenderPassDescriptor struct {
	Label                  string
	ColorAttachments       []RenderPassColorAttachment
	DepthStencilAttachment RenderPassDepthStencilAttachment
	OcclusionQuerySet      QuerySet
	TimestampWrites        PassTimestampWrites
}

type VertexState struct {
	Module     ShaderModule
	EntryPoint string
	Constants  []ConstantEntry
	Buffers    []VertexBufferLayout
}

type FragmentState struct {
	Module     ShaderModule
	EntryPoint string
	Constants  []ConstantEntry
	Targets    []ColorTargetState
}

type RenderPipelineDescriptor struct {
	Label        string
	Layout       PipelineLayout
	Vertex       VertexState
	Primitive    PrimitiveState
	DepthStencil DepthStencilState
	Multisample  MultisampleState
	Fragment     FragmentState
}

// GPU is the main interface for WebGPU operations
type GPU interface {
	CreateInstance(descriptor InstanceDescriptor) (Instance, error)

	GetInstanceFeatures(features SupportedInstanceFeatures) error

	GetInstanceLimits(limits InstanceLimits) (Status, error)

	HasInstanceFeature(feature InstanceFeatureName) (bool, error)
}

// Adapter interface
type Adapter interface {
	GetFeatures(features SupportedFeatures) error
	GetInfo(info AdapterInfo) (Status, error)
	GetLimits(limits Limits) (Status, error)
	HasFeature(feature FeatureName) (bool, error)
	RequestDevice(descriptor DeviceDescriptor, callback RequestDeviceCallbackInfo) Future
	AddRef() error
	Release() error
}

// BindGroup interface
type BindGroup interface {
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// BindGroupLayout interface
type BindGroupLayout interface {
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// Buffer interface
type Buffer interface {
	Destroy() error
	GetConstMappedRange(offset uintptr, size uintptr) (unsafe.Pointer, error)
	GetMappedRange(offset uintptr, size uintptr) (unsafe.Pointer, error)
	GetMapState() (BufferMapState, error)
	GetSize() (uint64, error)
	GetUsage() (BufferUsage, error)
	MapAsync(mode MapMode, offset uintptr, size uintptr, callback BufferMapCallbackInfo) Future
	ReadMappedRange(offset uintptr, data unsafe.Pointer, size uintptr) (Status, error)
	SetLabel(label string) error
	Unmap() error
	WriteMappedRange(offset uintptr, data unsafe.Pointer, size uintptr) (Status, error)
	AddRef() error
	Release() error
}

// CommandBuffer interface
type CommandBuffer interface {
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// CommandEncoder interface
type CommandEncoder interface {
	BeginComputePass(descriptor ComputePassDescriptor) (ComputePassEncoder, error)
	BeginRenderPass(descriptor RenderPassDescriptor) (RenderPassEncoder, error)
	ClearBuffer(buffer Buffer, offset uint64, size uint64) error
	CopyBufferToBuffer(source Buffer, sourceOffset uint64, destination Buffer, destinationOffset uint64, size uint64) error
	CopyBufferToTexture(source TexelCopyBufferInfo, destination TexelCopyTextureInfo, copySize Extent3D) error
	CopyTextureToBuffer(source TexelCopyTextureInfo, destination TexelCopyBufferInfo, copySize Extent3D) error
	CopyTextureToTexture(source TexelCopyTextureInfo, destination TexelCopyTextureInfo, copySize Extent3D) error
	Finish(descriptor CommandBufferDescriptor) (CommandBuffer, error)
	InsertDebugMarker(markerLabel string) error
	PopDebugGroup() error
	PushDebugGroup(groupLabel string) error
	ResolveQuerySet(querySet QuerySet, firstQuery uint32, queryCount uint32, destination Buffer, destinationOffset uint64) error
	SetLabel(label string) error
	WriteTimestamp(querySet QuerySet, queryIndex uint32) error
	AddRef() error
	Release() error
}

// ComputePassEncoder interface
type ComputePassEncoder interface {
	DispatchWorkgroups(workgroupCountX uint32, workgroupCountY uint32, workgroupCountZ uint32) error
	DispatchWorkgroupsIndirect(indirectBuffer Buffer, indirectOffset uint64) error
	End() error
	InsertDebugMarker(markerLabel string) error
	PopDebugGroup() error
	PushDebugGroup(groupLabel string) error
	SetBindGroup(groupIndex uint32, group BindGroup, dynamicOffsets []uint32) error
	SetLabel(label string) error
	SetPipeline(pipeline ComputePipeline) error
	AddRef() error
	Release() error
}

// ComputePipeline interface
type ComputePipeline interface {
	GetBindGroupLayout(groupIndex uint32) (BindGroupLayout, error)
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// TODO
//
// Releasing the last ref to a `WGPUDevice` also calls @ref wgpuDeviceDestroy.
// For more info, see @ref DeviceRelease.
// Device interface
type Device interface {
	CreateBindGroup(descriptor BindGroupDescriptor) (BindGroup, error)
	CreateBindGroupLayout(descriptor BindGroupLayoutDescriptor) (BindGroupLayout, error)
	CreateBuffer(descriptor BufferDescriptor) (Buffer, error)
	CreateCommandEncoder(descriptor CommandEncoderDescriptor) (CommandEncoder, error)
	CreateComputePipeline(descriptor ComputePipelineDescriptor) (ComputePipeline, error)
	CreateComputePipelineAsync(descriptor ComputePipelineDescriptor, callback CreateComputePipelineAsyncCallbackInfo) Future
	CreatePipelineLayout(descriptor PipelineLayoutDescriptor) (PipelineLayout, error)
	CreateQuerySet(descriptor QuerySetDescriptor) (QuerySet, error)
	CreateRenderBundleEncoder(descriptor RenderBundleEncoderDescriptor) (RenderBundleEncoder, error)
	CreateRenderPipeline(descriptor RenderPipelineDescriptor) (RenderPipeline, error)
	CreateRenderPipelineAsync(descriptor RenderPipelineDescriptor, callback CreateRenderPipelineAsyncCallbackInfo) Future
	CreateSampler(descriptor SamplerDescriptor) (Sampler, error)
	CreateShaderModule(descriptor ShaderModuleDescriptor) (ShaderModule, error)
	CreateTexture(descriptor TextureDescriptor) (Texture, error)
	Destroy() error
	GetAdapterInfo(adapterInfo AdapterInfo) (Status, error)
	GetFeatures(features SupportedFeatures) error
	GetLimits(limits Limits) (Status, error)
	GetLostFuture() (Future, error)
	GetQueue() (Queue, error)
	HasFeature(feature FeatureName) (bool, error)
	PopErrorScope(callback PopErrorScopeCallbackInfo) Future
	PushErrorScope(filter ErrorFilter) error
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// Instance interface
type Instance interface {
	CreateSurface(descriptor SurfaceDescriptor) (Surface, error)
	GetWGSLLanguageFeatures(features SupportedWGSLLanguageFeatures) (Status, error)
	HasWGSLLanguageFeature(feature WGSLLanguageFeatureName) (bool, error)
	ProcessEvents() error
	RequestAdapter(options RequestAdapterOptions, callback RequestAdapterCallbackInfo) Future
	WaitAny(futureCount uintptr, futures FutureWaitInfo, timeoutNS uint64) (WaitStatus, error)
	AddRef() error
	Release() error
}

// PipelineLayout interface
type PipelineLayout interface {
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// QuerySet interface
type QuerySet interface {
	Destroy() error
	GetCount() (uint32, error)
	GetType() (QueryType, error)
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// Queue interface
type Queue interface {
	OnSubmittedWorkDone(callback QueueWorkDoneCallbackInfo) Future
	SetLabel(label string) error
	Submit(commands []CommandBuffer) error
	WriteBuffer(buffer Buffer, bufferOffset uint64, data unsafe.Pointer, size uintptr) error
	WriteTexture(destination TexelCopyTextureInfo, data unsafe.Pointer, dataSize uintptr, dataLayout TexelCopyBufferLayout, writeSize Extent3D) error
	AddRef() error
	Release() error
}

// RenderBundle interface
type RenderBundle interface {
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// RenderBundleEncoder interface
type RenderBundleEncoder interface {
	Draw(vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) error
	DrawIndexed(indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) error
	DrawIndexedIndirect(indirectBuffer Buffer, indirectOffset uint64) error
	DrawIndirect(indirectBuffer Buffer, indirectOffset uint64) error
	Finish(descriptor RenderBundleDescriptor) (RenderBundle, error)
	InsertDebugMarker(markerLabel string) error
	PopDebugGroup() error
	PushDebugGroup(groupLabel string) error
	SetBindGroup(groupIndex uint32, group BindGroup, dynamicOffsets []uint32) error
	SetIndexBuffer(buffer Buffer, format IndexFormat, offset uint64, size uint64) error
	SetLabel(label string) error
	SetPipeline(pipeline RenderPipeline) error
	SetVertexBuffer(slot uint32, buffer Buffer, offset uint64, size uint64) error
	AddRef() error
	Release() error
}

// RenderPassEncoder interface
type RenderPassEncoder interface {
	BeginOcclusionQuery(queryIndex uint32) error
	Draw(vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) error
	DrawIndexed(indexCount uint32, instanceCount uint32, firstIndex uint32, baseVertex int32, firstInstance uint32) error
	DrawIndexedIndirect(indirectBuffer Buffer, indirectOffset uint64) error
	DrawIndirect(indirectBuffer Buffer, indirectOffset uint64) error
	End() error
	EndOcclusionQuery() error
	ExecuteBundles(bundles []RenderBundle) error
	InsertDebugMarker(markerLabel string) error
	PopDebugGroup() error
	PushDebugGroup(groupLabel string) error
	SetBindGroup(groupIndex uint32, group BindGroup, dynamicOffsets []uint32) error
	SetBlendConstant(color Color) error
	SetIndexBuffer(buffer Buffer, format IndexFormat, offset uint64, size uint64) error
	SetLabel(label string) error
	SetPipeline(pipeline RenderPipeline) error
	SetScissorRect(x uint32, y uint32, width uint32, height uint32) error
	SetStencilReference(reference uint32) error
	SetVertexBuffer(slot uint32, buffer Buffer, offset uint64, size uint64) error
	SetViewport(x float32, y float32, width float32, height float32, minDepth float32, maxDepth float32) error
	AddRef() error
	Release() error
}

// RenderPipeline interface
type RenderPipeline interface {
	GetBindGroupLayout(groupIndex uint32) (BindGroupLayout, error)
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// Sampler interface
type Sampler interface {
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// ShaderModule interface
type ShaderModule interface {
	GetCompilationInfo(callback CompilationInfoCallbackInfo) Future
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// An object used to continuously present image data to the user, see @ref Surfaces for more details.
// Surface interface
type Surface interface {
	Configure(config SurfaceConfiguration) error
	GetCapabilities(adapter Adapter, capabilities SurfaceCapabilities) (Status, error)
	GetCurrentTexture(surfaceTexture SurfaceTexture) error
	Present() (Status, error)
	SetLabel(label string) error
	Unconfigure() error
	AddRef() error
	Release() error
}

// Texture interface
type Texture interface {
	CreateView(descriptor TextureViewDescriptor) (TextureView, error)
	Destroy() error
	GetDepthOrArrayLayers() (uint32, error)
	GetDimension() (TextureDimension, error)
	GetFormat() (TextureFormat, error)
	GetHeight() (uint32, error)
	GetMipLevelCount() (uint32, error)
	GetSampleCount() (uint32, error)
	GetUsage() (TextureUsage, error)
	GetWidth() (uint32, error)
	SetLabel(label string) error
	AddRef() error
	Release() error
}

// TextureView interface
type TextureView interface {
	SetLabel(label string) error
	AddRef() error
	Release() error
}
