// Code generated by "stringer -type=KeyCode -trimprefix=KeyCode -output=keyboard_string.go"; DO NOT EDIT.

package gio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyCodeUnknown-0]
	_ = x[KeyCodeEscape-1]
	_ = x[KeyCodeTab-15]
	_ = x[KeyCodeCapsLock-58]
	_ = x[KeyCodeBackspace-14]
	_ = x[KeyCodeEnter-28]
	_ = x[KeyCodeSpace-57]
	_ = x[KeyCodeShiftLeft-42]
	_ = x[KeyCodeShiftRight-54]
	_ = x[KeyCodeControlLeft-29]
	_ = x[KeyCodeControlRight-57373]
	_ = x[KeyCodeAltLeft-56]
	_ = x[KeyCodeAltRight-57400]
	_ = x[KeyCodeMetaLeft-57435]
	_ = x[KeyCodeMetaRight-57436]
	_ = x[KeyCodeDigit1-2]
	_ = x[KeyCodeDigit2-3]
	_ = x[KeyCodeDigit3-4]
	_ = x[KeyCodeDigit4-5]
	_ = x[KeyCodeDigit5-6]
	_ = x[KeyCodeDigit6-7]
	_ = x[KeyCodeDigit7-8]
	_ = x[KeyCodeDigit8-9]
	_ = x[KeyCodeDigit9-10]
	_ = x[KeyCodeDigit0-11]
	_ = x[KeyCodeMinus-12]
	_ = x[KeyCodeEqual-13]
	_ = x[KeyCodeF1-59]
	_ = x[KeyCodeF2-60]
	_ = x[KeyCodeF3-61]
	_ = x[KeyCodeF4-62]
	_ = x[KeyCodeF5-63]
	_ = x[KeyCodeF6-64]
	_ = x[KeyCodeF7-65]
	_ = x[KeyCodeF8-66]
	_ = x[KeyCodeF9-67]
	_ = x[KeyCodeF10-68]
	_ = x[KeyCodeF11-87]
	_ = x[KeyCodeF12-88]
	_ = x[KeyCodeKeyA-30]
	_ = x[KeyCodeKeyB-48]
	_ = x[KeyCodeKeyC-46]
	_ = x[KeyCodeKeyD-32]
	_ = x[KeyCodeKeyE-18]
	_ = x[KeyCodeKeyF-33]
	_ = x[KeyCodeKeyG-34]
	_ = x[KeyCodeKeyH-35]
	_ = x[KeyCodeKeyI-23]
	_ = x[KeyCodeKeyJ-36]
	_ = x[KeyCodeKeyK-37]
	_ = x[KeyCodeKeyL-38]
	_ = x[KeyCodeKeyM-50]
	_ = x[KeyCodeKeyN-49]
	_ = x[KeyCodeKeyO-24]
	_ = x[KeyCodeKeyP-25]
	_ = x[KeyCodeKeyQ-16]
	_ = x[KeyCodeKeyR-19]
	_ = x[KeyCodeKeyS-31]
	_ = x[KeyCodeKeyT-20]
	_ = x[KeyCodeKeyU-22]
	_ = x[KeyCodeKeyV-47]
	_ = x[KeyCodeKeyW-17]
	_ = x[KeyCodeKeyX-45]
	_ = x[KeyCodeKeyY-21]
	_ = x[KeyCodeKeyZ-44]
	_ = x[KeyCodeBracketLeft-26]
	_ = x[KeyCodeBracketRight-27]
	_ = x[KeyCodeBackslash-43]
	_ = x[KeyCodeSemicolon-39]
	_ = x[KeyCodeQuote-40]
	_ = x[KeyCodeBackquote-41]
	_ = x[KeyCodeComma-51]
	_ = x[KeyCodePeriod-52]
	_ = x[KeyCodeSlash-53]
	_ = x[KeyCodeInsert-57426]
	_ = x[KeyCodeDelete-57427]
	_ = x[KeyCodeHome-57415]
	_ = x[KeyCodeEnd-57423]
	_ = x[KeyCodePageUp-57417]
	_ = x[KeyCodePageDown-57425]
	_ = x[KeyCodeArrowUp-57416]
	_ = x[KeyCodeArrowDown-57424]
	_ = x[KeyCodeArrowLeft-57419]
	_ = x[KeyCodeArrowRight-57421]
	_ = x[KeyCodeNumLock-57413]
	_ = x[KeyCodeNumpadDivide-57397]
	_ = x[KeyCodeNumpadMultiply-55]
	_ = x[KeyCodeNumpadSubtract-74]
	_ = x[KeyCodeNumpadAdd-78]
	_ = x[KeyCodeNumpadEnter-57372]
	_ = x[KeyCodeNumpad1-79]
	_ = x[KeyCodeNumpad2-80]
	_ = x[KeyCodeNumpad3-81]
	_ = x[KeyCodeNumpad4-75]
	_ = x[KeyCodeNumpad5-76]
	_ = x[KeyCodeNumpad6-77]
	_ = x[KeyCodeNumpad7-71]
	_ = x[KeyCodeNumpad8-72]
	_ = x[KeyCodeNumpad9-73]
	_ = x[KeyCodeNumpad0-82]
	_ = x[KeyCodeNumpadDecimal-83]
	_ = x[KeyCodeNumpadEqual-89]
	_ = x[KeyCodeNumpadComma-126]
	_ = x[KeyCodeScrollLock-70]
	_ = x[KeyCodePause-69]
	_ = x[KeyCodePrintScreen-57399]
	_ = x[KeyCodeContextMenu-57437]
	_ = x[KeyCodeMediaTrackPrevious-57360]
	_ = x[KeyCodeMediaTrackNext-57369]
	_ = x[KeyCodeMediaPlayPause-57378]
	_ = x[KeyCodeMediaStop-57380]
	_ = x[KeyCodeAudioVolumeMute-57376]
	_ = x[KeyCodeAudioVolumeDown-57390]
	_ = x[KeyCodeAudioVolumeUp-57392]
	_ = x[KeyCodeBrowserHome-57394]
	_ = x[KeyCodeBrowserSearch-57445]
	_ = x[KeyCodeBrowserFavorites-57446]
	_ = x[KeyCodeBrowserRefresh-57447]
	_ = x[KeyCodeBrowserStop-57448]
	_ = x[KeyCodeBrowserForward-57449]
	_ = x[KeyCodeBrowserBack-57450]
	_ = x[KeyCodeIntlBackslash-86]
	_ = x[KeyCodeIntlRo-115]
	_ = x[KeyCodeIntlYen-125]
	_ = x[KeyCodeLang1-114]
	_ = x[KeyCodeLang2-113]
	_ = x[KeyCodeLang3-120]
	_ = x[KeyCodeLang4-119]
	_ = x[KeyCodeKanaMode-112]
	_ = x[KeyCodeConvert-121]
	_ = x[KeyCodeNonConvert-123]
	_ = x[KeyCodePower-57438]
	_ = x[KeyCodeSleep-57439]
	_ = x[KeyCodeWakeUp-57443]
	_ = x[KeyCodeLaunchApp1-57451]
	_ = x[KeyCodeLaunchApp2-57377]
	_ = x[KeyCodeLaunchMail-57452]
	_ = x[KeyCodeMediaSelect-57453]
}

const _KeyCode_name = "UnknownEscapeDigit1Digit2Digit3Digit4Digit5Digit6Digit7Digit8Digit9Digit0MinusEqualBackspaceTabKeyQKeyWKeyEKeyRKeyTKeyYKeyUKeyIKeyOKeyPBracketLeftBracketRightEnterControlLeftKeyAKeySKeyDKeyFKeyGKeyHKeyJKeyKKeyLSemicolonQuoteBackquoteShiftLeftBackslashKeyZKeyXKeyCKeyVKeyBKeyNKeyMCommaPeriodSlashShiftRightNumpadMultiplyAltLeftSpaceCapsLockF1F2F3F4F5F6F7F8F9F10PauseScrollLockNumpad7Numpad8Numpad9NumpadSubtractNumpad4Numpad5Numpad6NumpadAddNumpad1Numpad2Numpad3Numpad0NumpadDecimalIntlBackslashF11F12NumpadEqualKanaModeLang2Lang1IntlRoLang4Lang3ConvertNonConvertIntlYenNumpadCommaMediaTrackPreviousMediaTrackNextNumpadEnterControlRightAudioVolumeMuteLaunchApp2MediaPlayPauseMediaStopAudioVolumeDownAudioVolumeUpBrowserHomeNumpadDividePrintScreenAltRightNumLockHomeArrowUpPageUpArrowLeftArrowRightEndArrowDownPageDownInsertDeleteMetaLeftMetaRightContextMenuPowerSleepWakeUpBrowserSearchBrowserFavoritesBrowserRefreshBrowserStopBrowserForwardBrowserBackLaunchApp1LaunchMailMediaSelect"

var _KeyCode_map = map[KeyCode]string{
	0:     _KeyCode_name[0:7],
	1:     _KeyCode_name[7:13],
	2:     _KeyCode_name[13:19],
	3:     _KeyCode_name[19:25],
	4:     _KeyCode_name[25:31],
	5:     _KeyCode_name[31:37],
	6:     _KeyCode_name[37:43],
	7:     _KeyCode_name[43:49],
	8:     _KeyCode_name[49:55],
	9:     _KeyCode_name[55:61],
	10:    _KeyCode_name[61:67],
	11:    _KeyCode_name[67:73],
	12:    _KeyCode_name[73:78],
	13:    _KeyCode_name[78:83],
	14:    _KeyCode_name[83:92],
	15:    _KeyCode_name[92:95],
	16:    _KeyCode_name[95:99],
	17:    _KeyCode_name[99:103],
	18:    _KeyCode_name[103:107],
	19:    _KeyCode_name[107:111],
	20:    _KeyCode_name[111:115],
	21:    _KeyCode_name[115:119],
	22:    _KeyCode_name[119:123],
	23:    _KeyCode_name[123:127],
	24:    _KeyCode_name[127:131],
	25:    _KeyCode_name[131:135],
	26:    _KeyCode_name[135:146],
	27:    _KeyCode_name[146:158],
	28:    _KeyCode_name[158:163],
	29:    _KeyCode_name[163:174],
	30:    _KeyCode_name[174:178],
	31:    _KeyCode_name[178:182],
	32:    _KeyCode_name[182:186],
	33:    _KeyCode_name[186:190],
	34:    _KeyCode_name[190:194],
	35:    _KeyCode_name[194:198],
	36:    _KeyCode_name[198:202],
	37:    _KeyCode_name[202:206],
	38:    _KeyCode_name[206:210],
	39:    _KeyCode_name[210:219],
	40:    _KeyCode_name[219:224],
	41:    _KeyCode_name[224:233],
	42:    _KeyCode_name[233:242],
	43:    _KeyCode_name[242:251],
	44:    _KeyCode_name[251:255],
	45:    _KeyCode_name[255:259],
	46:    _KeyCode_name[259:263],
	47:    _KeyCode_name[263:267],
	48:    _KeyCode_name[267:271],
	49:    _KeyCode_name[271:275],
	50:    _KeyCode_name[275:279],
	51:    _KeyCode_name[279:284],
	52:    _KeyCode_name[284:290],
	53:    _KeyCode_name[290:295],
	54:    _KeyCode_name[295:305],
	55:    _KeyCode_name[305:319],
	56:    _KeyCode_name[319:326],
	57:    _KeyCode_name[326:331],
	58:    _KeyCode_name[331:339],
	59:    _KeyCode_name[339:341],
	60:    _KeyCode_name[341:343],
	61:    _KeyCode_name[343:345],
	62:    _KeyCode_name[345:347],
	63:    _KeyCode_name[347:349],
	64:    _KeyCode_name[349:351],
	65:    _KeyCode_name[351:353],
	66:    _KeyCode_name[353:355],
	67:    _KeyCode_name[355:357],
	68:    _KeyCode_name[357:360],
	69:    _KeyCode_name[360:365],
	70:    _KeyCode_name[365:375],
	71:    _KeyCode_name[375:382],
	72:    _KeyCode_name[382:389],
	73:    _KeyCode_name[389:396],
	74:    _KeyCode_name[396:410],
	75:    _KeyCode_name[410:417],
	76:    _KeyCode_name[417:424],
	77:    _KeyCode_name[424:431],
	78:    _KeyCode_name[431:440],
	79:    _KeyCode_name[440:447],
	80:    _KeyCode_name[447:454],
	81:    _KeyCode_name[454:461],
	82:    _KeyCode_name[461:468],
	83:    _KeyCode_name[468:481],
	86:    _KeyCode_name[481:494],
	87:    _KeyCode_name[494:497],
	88:    _KeyCode_name[497:500],
	89:    _KeyCode_name[500:511],
	112:   _KeyCode_name[511:519],
	113:   _KeyCode_name[519:524],
	114:   _KeyCode_name[524:529],
	115:   _KeyCode_name[529:535],
	119:   _KeyCode_name[535:540],
	120:   _KeyCode_name[540:545],
	121:   _KeyCode_name[545:552],
	123:   _KeyCode_name[552:562],
	125:   _KeyCode_name[562:569],
	126:   _KeyCode_name[569:580],
	57360: _KeyCode_name[580:598],
	57369: _KeyCode_name[598:612],
	57372: _KeyCode_name[612:623],
	57373: _KeyCode_name[623:635],
	57376: _KeyCode_name[635:650],
	57377: _KeyCode_name[650:660],
	57378: _KeyCode_name[660:674],
	57380: _KeyCode_name[674:683],
	57390: _KeyCode_name[683:698],
	57392: _KeyCode_name[698:711],
	57394: _KeyCode_name[711:722],
	57397: _KeyCode_name[722:734],
	57399: _KeyCode_name[734:745],
	57400: _KeyCode_name[745:753],
	57413: _KeyCode_name[753:760],
	57415: _KeyCode_name[760:764],
	57416: _KeyCode_name[764:771],
	57417: _KeyCode_name[771:777],
	57419: _KeyCode_name[777:786],
	57421: _KeyCode_name[786:796],
	57423: _KeyCode_name[796:799],
	57424: _KeyCode_name[799:808],
	57425: _KeyCode_name[808:816],
	57426: _KeyCode_name[816:822],
	57427: _KeyCode_name[822:828],
	57435: _KeyCode_name[828:836],
	57436: _KeyCode_name[836:845],
	57437: _KeyCode_name[845:856],
	57438: _KeyCode_name[856:861],
	57439: _KeyCode_name[861:866],
	57443: _KeyCode_name[866:872],
	57445: _KeyCode_name[872:885],
	57446: _KeyCode_name[885:901],
	57447: _KeyCode_name[901:915],
	57448: _KeyCode_name[915:926],
	57449: _KeyCode_name[926:940],
	57450: _KeyCode_name[940:951],
	57451: _KeyCode_name[951:961],
	57452: _KeyCode_name[961:971],
	57453: _KeyCode_name[971:982],
}

func (i KeyCode) String() string {
	if str, ok := _KeyCode_map[i]; ok {
		return str
	}
	return "KeyCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
