// Code generated by "stringer -type=KeyCode,KeyAction,MouseButton,ModifierKey,JoystickAction --trimprefix=Key,KeyAction,MouseButton,Mod,Joystick --output=keyboard_string.go"; DO NOT EDIT.

package gio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyUnknown - -1]
	_ = x[KeySpace-32]
	_ = x[KeyApostrophe-39]
	_ = x[KeyComma-44]
	_ = x[KeyMinus-45]
	_ = x[KeyPeriod-46]
	_ = x[KeySlash-47]
	_ = x[Key0-48]
	_ = x[Key1-49]
	_ = x[Key2-50]
	_ = x[Key3-51]
	_ = x[Key4-52]
	_ = x[Key5-53]
	_ = x[Key6-54]
	_ = x[Key7-55]
	_ = x[Key8-56]
	_ = x[Key9-57]
	_ = x[KeySemicolon-59]
	_ = x[KeyEqual-61]
	_ = x[KeyA-65]
	_ = x[KeyB-66]
	_ = x[KeyC-67]
	_ = x[KeyD-68]
	_ = x[KeyE-69]
	_ = x[KeyF-70]
	_ = x[KeyG-71]
	_ = x[KeyH-72]
	_ = x[KeyI-73]
	_ = x[KeyJ-74]
	_ = x[KeyK-75]
	_ = x[KeyL-76]
	_ = x[KeyM-77]
	_ = x[KeyN-78]
	_ = x[KeyO-79]
	_ = x[KeyP-80]
	_ = x[KeyQ-81]
	_ = x[KeyR-82]
	_ = x[KeyS-83]
	_ = x[KeyT-84]
	_ = x[KeyU-85]
	_ = x[KeyV-86]
	_ = x[KeyW-87]
	_ = x[KeyX-88]
	_ = x[KeyY-89]
	_ = x[KeyZ-90]
	_ = x[KeyLeftBracket-91]
	_ = x[KeyBackslash-92]
	_ = x[KeyRightBracket-93]
	_ = x[KeyGraveAccent-96]
	_ = x[KeyWorld1-161]
	_ = x[KeyWorld2-162]
	_ = x[KeyEscape-256]
	_ = x[KeyEnter-257]
	_ = x[KeyTab-258]
	_ = x[KeyBackspace-259]
	_ = x[KeyInsert-260]
	_ = x[KeyDelete-261]
	_ = x[KeyRight-262]
	_ = x[KeyLeft-263]
	_ = x[KeyDown-264]
	_ = x[KeyUp-265]
	_ = x[KeyPageUp-266]
	_ = x[KeyPageDown-267]
	_ = x[KeyHome-268]
	_ = x[KeyEnd-269]
	_ = x[KeyCapsLock-280]
	_ = x[KeyScrollLock-281]
	_ = x[KeyNumLock-282]
	_ = x[KeyPrintScreen-283]
	_ = x[KeyPause-284]
	_ = x[KeyF1-290]
	_ = x[KeyF2-291]
	_ = x[KeyF3-292]
	_ = x[KeyF4-293]
	_ = x[KeyF5-294]
	_ = x[KeyF6-295]
	_ = x[KeyF7-296]
	_ = x[KeyF8-297]
	_ = x[KeyF9-298]
	_ = x[KeyF10-299]
	_ = x[KeyF11-300]
	_ = x[KeyF12-301]
	_ = x[KeyF13-302]
	_ = x[KeyF14-303]
	_ = x[KeyF15-304]
	_ = x[KeyF16-305]
	_ = x[KeyF17-306]
	_ = x[KeyF18-307]
	_ = x[KeyF19-308]
	_ = x[KeyF20-309]
	_ = x[KeyF21-310]
	_ = x[KeyF22-311]
	_ = x[KeyF23-312]
	_ = x[KeyF24-313]
	_ = x[KeyF25-314]
	_ = x[KeyKp0-320]
	_ = x[KeyKp1-321]
	_ = x[KeyKp2-322]
	_ = x[KeyKp3-323]
	_ = x[KeyKp4-324]
	_ = x[KeyKp5-325]
	_ = x[KeyKp6-326]
	_ = x[KeyKp7-327]
	_ = x[KeyKp8-328]
	_ = x[KeyKp9-329]
	_ = x[KeyKpDecimal-330]
	_ = x[KeyKpDivide-331]
	_ = x[KeyKpMultiply-332]
	_ = x[KeyKpSubtract-333]
	_ = x[KeyKpAdd-334]
	_ = x[KeyKpEnter-335]
	_ = x[KeyKpEqual-336]
	_ = x[KeyLeftShift-340]
	_ = x[KeyLeftControl-341]
	_ = x[KeyLeftAlt-342]
	_ = x[KeyLeftSuper-343]
	_ = x[KeyRightShift-344]
	_ = x[KeyRightControl-345]
	_ = x[KeyRightAlt-346]
	_ = x[KeyRightSuper-347]
	_ = x[KeyMenu-348]
}

const _KeyCode_name = "KeyUnknownKeySpaceKeyApostropheKeyCommaKeyMinusKeyPeriodKeySlashKey0Key1Key2Key3Key4Key5Key6Key7Key8Key9KeySemicolonKeyEqualKeyAKeyBKeyCKeyDKeyEKeyFKeyGKeyHKeyIKeyJKeyKKeyLKeyMKeyNKeyOKeyPKeyQKeyRKeySKeyTKeyUKeyVKeyWKeyXKeyYKeyZKeyLeftBracketKeyBackslashKeyRightBracketKeyGraveAccentKeyWorld1KeyWorld2KeyEscapeKeyEnterKeyTabKeyBackspaceKeyInsertKeyDeleteKeyRightKeyLeftKeyDownKeyUpKeyPageUpKeyPageDownKeyHomeKeyEndKeyCapsLockKeyScrollLockKeyNumLockKeyPrintScreenKeyPauseKeyF1KeyF2KeyF3KeyF4KeyF5KeyF6KeyF7KeyF8KeyF9KeyF10KeyF11KeyF12KeyF13KeyF14KeyF15KeyF16KeyF17KeyF18KeyF19KeyF20KeyF21KeyF22KeyF23KeyF24KeyF25KeyKp0KeyKp1KeyKp2KeyKp3KeyKp4KeyKp5KeyKp6KeyKp7KeyKp8KeyKp9KeyKpDecimalKeyKpDivideKeyKpMultiplyKeyKpSubtractKeyKpAddKeyKpEnterKeyKpEqualKeyLeftShiftKeyLeftControlKeyLeftAltKeyLeftSuperKeyRightShiftKeyRightControlKeyRightAltKeyRightSuperKeyMenu"

var _KeyCode_map = map[KeyCode]string{
	-1:  _KeyCode_name[0:10],
	32:  _KeyCode_name[10:18],
	39:  _KeyCode_name[18:31],
	44:  _KeyCode_name[31:39],
	45:  _KeyCode_name[39:47],
	46:  _KeyCode_name[47:56],
	47:  _KeyCode_name[56:64],
	48:  _KeyCode_name[64:68],
	49:  _KeyCode_name[68:72],
	50:  _KeyCode_name[72:76],
	51:  _KeyCode_name[76:80],
	52:  _KeyCode_name[80:84],
	53:  _KeyCode_name[84:88],
	54:  _KeyCode_name[88:92],
	55:  _KeyCode_name[92:96],
	56:  _KeyCode_name[96:100],
	57:  _KeyCode_name[100:104],
	59:  _KeyCode_name[104:116],
	61:  _KeyCode_name[116:124],
	65:  _KeyCode_name[124:128],
	66:  _KeyCode_name[128:132],
	67:  _KeyCode_name[132:136],
	68:  _KeyCode_name[136:140],
	69:  _KeyCode_name[140:144],
	70:  _KeyCode_name[144:148],
	71:  _KeyCode_name[148:152],
	72:  _KeyCode_name[152:156],
	73:  _KeyCode_name[156:160],
	74:  _KeyCode_name[160:164],
	75:  _KeyCode_name[164:168],
	76:  _KeyCode_name[168:172],
	77:  _KeyCode_name[172:176],
	78:  _KeyCode_name[176:180],
	79:  _KeyCode_name[180:184],
	80:  _KeyCode_name[184:188],
	81:  _KeyCode_name[188:192],
	82:  _KeyCode_name[192:196],
	83:  _KeyCode_name[196:200],
	84:  _KeyCode_name[200:204],
	85:  _KeyCode_name[204:208],
	86:  _KeyCode_name[208:212],
	87:  _KeyCode_name[212:216],
	88:  _KeyCode_name[216:220],
	89:  _KeyCode_name[220:224],
	90:  _KeyCode_name[224:228],
	91:  _KeyCode_name[228:242],
	92:  _KeyCode_name[242:254],
	93:  _KeyCode_name[254:269],
	96:  _KeyCode_name[269:283],
	161: _KeyCode_name[283:292],
	162: _KeyCode_name[292:301],
	256: _KeyCode_name[301:310],
	257: _KeyCode_name[310:318],
	258: _KeyCode_name[318:324],
	259: _KeyCode_name[324:336],
	260: _KeyCode_name[336:345],
	261: _KeyCode_name[345:354],
	262: _KeyCode_name[354:362],
	263: _KeyCode_name[362:369],
	264: _KeyCode_name[369:376],
	265: _KeyCode_name[376:381],
	266: _KeyCode_name[381:390],
	267: _KeyCode_name[390:401],
	268: _KeyCode_name[401:408],
	269: _KeyCode_name[408:414],
	280: _KeyCode_name[414:425],
	281: _KeyCode_name[425:438],
	282: _KeyCode_name[438:448],
	283: _KeyCode_name[448:462],
	284: _KeyCode_name[462:470],
	290: _KeyCode_name[470:475],
	291: _KeyCode_name[475:480],
	292: _KeyCode_name[480:485],
	293: _KeyCode_name[485:490],
	294: _KeyCode_name[490:495],
	295: _KeyCode_name[495:500],
	296: _KeyCode_name[500:505],
	297: _KeyCode_name[505:510],
	298: _KeyCode_name[510:515],
	299: _KeyCode_name[515:521],
	300: _KeyCode_name[521:527],
	301: _KeyCode_name[527:533],
	302: _KeyCode_name[533:539],
	303: _KeyCode_name[539:545],
	304: _KeyCode_name[545:551],
	305: _KeyCode_name[551:557],
	306: _KeyCode_name[557:563],
	307: _KeyCode_name[563:569],
	308: _KeyCode_name[569:575],
	309: _KeyCode_name[575:581],
	310: _KeyCode_name[581:587],
	311: _KeyCode_name[587:593],
	312: _KeyCode_name[593:599],
	313: _KeyCode_name[599:605],
	314: _KeyCode_name[605:611],
	320: _KeyCode_name[611:617],
	321: _KeyCode_name[617:623],
	322: _KeyCode_name[623:629],
	323: _KeyCode_name[629:635],
	324: _KeyCode_name[635:641],
	325: _KeyCode_name[641:647],
	326: _KeyCode_name[647:653],
	327: _KeyCode_name[653:659],
	328: _KeyCode_name[659:665],
	329: _KeyCode_name[665:671],
	330: _KeyCode_name[671:683],
	331: _KeyCode_name[683:694],
	332: _KeyCode_name[694:707],
	333: _KeyCode_name[707:720],
	334: _KeyCode_name[720:728],
	335: _KeyCode_name[728:738],
	336: _KeyCode_name[738:748],
	340: _KeyCode_name[748:760],
	341: _KeyCode_name[760:774],
	342: _KeyCode_name[774:784],
	343: _KeyCode_name[784:796],
	344: _KeyCode_name[796:809],
	345: _KeyCode_name[809:824],
	346: _KeyCode_name[824:835],
	347: _KeyCode_name[835:848],
	348: _KeyCode_name[848:855],
}

func (i KeyCode) String() string {
	if str, ok := _KeyCode_map[i]; ok {
		return str
	}
	return "KeyCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyActionRelease-0]
	_ = x[KeyActionPress-1]
	_ = x[KeyActionRepeat-2]
}

const _KeyAction_name = "KeyActionReleaseKeyActionPressKeyActionRepeat"

var _KeyAction_index = [...]uint8{0, 16, 30, 45}

func (i KeyAction) String() string {
	if i < 0 || i >= KeyAction(len(_KeyAction_index)-1) {
		return "KeyAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyAction_name[_KeyAction_index[i]:_KeyAction_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MouseButtonLeft-0]
	_ = x[MouseButtonRight-1]
	_ = x[MouseButtonMiddle-2]
	_ = x[MouseButton1-0]
	_ = x[MouseButton2-1]
	_ = x[MouseButton3-2]
	_ = x[MouseButton4-3]
	_ = x[MouseButton5-4]
	_ = x[MouseButton6-5]
	_ = x[MouseButton7-6]
	_ = x[MouseButton8-7]
}

const _MouseButton_name = "MouseButtonLeftMouseButtonRightMouseButtonMiddleMouseButton4MouseButton5MouseButton6MouseButton7MouseButton8"

var _MouseButton_index = [...]uint8{0, 15, 31, 48, 60, 72, 84, 96, 108}

func (i MouseButton) String() string {
	if i < 0 || i >= MouseButton(len(_MouseButton_index)-1) {
		return "MouseButton(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MouseButton_name[_MouseButton_index[i]:_MouseButton_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModShift-1]
	_ = x[ModControl-2]
	_ = x[ModAlt-4]
	_ = x[ModSuper-8]
	_ = x[ModCapsLock-16]
	_ = x[ModNumLock-32]
}

const (
	_ModifierKey_name_0 = "ModShiftModControl"
	_ModifierKey_name_1 = "ModAlt"
	_ModifierKey_name_2 = "ModSuper"
	_ModifierKey_name_3 = "ModCapsLock"
	_ModifierKey_name_4 = "ModNumLock"
)

var (
	_ModifierKey_index_0 = [...]uint8{0, 8, 18}
)

func (i ModifierKey) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ModifierKey_name_0[_ModifierKey_index_0[i]:_ModifierKey_index_0[i+1]]
	case i == 4:
		return _ModifierKey_name_1
	case i == 8:
		return _ModifierKey_name_2
	case i == 16:
		return _ModifierKey_name_3
	case i == 32:
		return _ModifierKey_name_4
	default:
		return "ModifierKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JoystickConnected-262145]
	_ = x[JoystickDisconnected-262146]
}

const _JoystickAction_name = "JoystickConnectedJoystickDisconnected"

var _JoystickAction_index = [...]uint8{0, 17, 37}

func (i JoystickAction) String() string {
	i -= 262145
	if i < 0 || i >= JoystickAction(len(_JoystickAction_index)-1) {
		return "JoystickAction(" + strconv.FormatInt(int64(i+262145), 10) + ")"
	}
	return _JoystickAction_name[_JoystickAction_index[i]:_JoystickAction_index[i+1]]
}
