// Code generated by gen.go. DO NOT EDIT.

{{ SCommentN .Copyright 0 }}

// Package gpu provides WebGPU implementation interfaces.
{{ SCommentN .Doc 0 -}}
package webgpu

import (
    "math"
    "unsafe"
)

// ===== Constants =====
const (
{{- range .Constants -}}
	{{- if ne .Value "nan" }}
    {{- SComment .Doc 1 -}}
    {{GoConstantName .Base}} = {{.Value | GoValue}}
	{{- end }}
{{ end -}}
)

var (
{{- range .Constants -}}
	{{- if eq .Value "nan" -}}
    {{- SComment .Doc 1 -}}
    {{GoConstantName .Base}} = {{.Value | GoValue}}
	{{- end -}}
{{ end -}}
)

// ===== Typedefs =====
{{ range .Typedefs}}
{{- SComment .Doc 0 -}}
type {{GoTypeName .Base}} {{GoType .Type}}
{{ end }}

// ===== Enums =====
{{ range $enum := .Enums}}
{{- if and (HasSuffix .Base.Name "_status") (ne .Base.Name "surface_get_current_texture_status") }} {{continue -}} {{end}}
{{- if eq .Base.Name "callback_mode"}} {{continue -}} {{end}}
{{- SComment .Doc 0 -}}
type {{GoTypeName .Base}} uint32

const (
{{- range $entryIndex, $_ := .Entries -}}
{{- if . -}}
    {{- SComment .Doc 1 -}}
    {{GoEnumName $enum.Base .Base}} {{GoTypeName $enum.Base}} = {{EnumValue32 $enum $entryIndex}}
{{ end -}}
{{ end -}}
)
{{ end }}

// ===== Bitflags =====
{{ range $bitflag := .Bitflags}}
{{- SComment .Doc 0 -}}
type {{GoTypeName .Base}} uint64

const (
{{ range $entryIndex, $_ := .Entries}}
    {{- SComment .Doc 1 -}}
    {{GoEnumName $bitflag.Base .Base}} {{GoTypeName $bitflag.Base}} = {{BitflagValue $bitflag $entryIndex}}
{{ end }}
)
{{ end }}

// ===== Structs =====
{{ range $struct := .Structs}}
{{- SComment .Doc 0 -}}
type {{GoTypeName .Base}} struct {
{{- range $memberIndex, $_ := .Members}}
{{- if (.Type | IsArray)}}
    {{GoStructMemberArray $struct $memberIndex -}}
{{ else if (.Type | IsCallback)}}
	{{continue -}}
{{ else }}
    {{GoStructMember $struct $memberIndex -}}
{{ end  -}}
{{ end -}}
}

{{ end }}

// GPU is the main interface for WebGPU operations
type GPU interface {
{{ range .Functions}}
    {{GoFunctionName .Base}}({{GoFunctionArgs . }}) {{GoFunctionReturns .}}
{{ end }}
}

// ===== Objects =====

// Instance interface
type Instance interface {
	CreateSurface(descriptor SurfaceDescriptor) (Surface, error)
	WGSLLanguageFeatures() (*SupportedWGSLLanguageFeatures, error)
	HasWGSLLanguageFeature(feature WGSLLanguageFeatureName) (bool, error)
	RequestAdapter(options RequestAdapterOptions) (Adapter, error)
}

{{ range $object := .Objects}}
{{- if eq .Base.Name "instance"}} {{continue -}} {{end}}

{{ if not .IsStruct}}
{{ if .Doc }}
{{- SComment .Doc 0 -}}
{{ end -}}
// {{GoTypeName $object.Base}} interface
type {{GoTypeName $object.Base}} interface {
{{- range $object.Methods }}
	{{- if HasSuffix .Base.Name "_async"}} {{continue -}} {{end}}
    {{GoFunctionName .Base}}({{GoFunctionArgs . }}) {{GoFunctionReturns . -}}
{{ end -}}
}
{{ end }}
{{ end }}
